(** * ChoiceTyping.LetResultWorld

    Resource worlds generated by evaluating an expression into a fresh result
    coordinate.  These lemmas keep the operational/result-world bookkeeping out
    of the main soundness helper file. *)

From CoreLang Require Import Instantiation InstantiationProps LocallyNamelessProps
  OperationalProps.
From ChoiceTyping Require Export Typing.

Definition let_result_raw_world_on
    (e : tm) (x : atom) (w : WfWorld) : World := {|
  world_dom := world_dom (w : World) ∪ {[x]};
  world_stores := fun σx =>
    ∃ σ vx,
      (w : World) σ ∧
      subst_map (store_restrict σ (fv_tm e)) e →* tret vx ∧
      σx = <[x := vx]> σ;
|}.

Lemma let_result_raw_world_on_wf e x (w : WfWorld) :
  x ∉ world_dom (w : World) →
  (∀ σ, (w : World) σ →
    ∃ vx, subst_map (store_restrict σ (fv_tm e)) e →* tret vx) →
  wf_world (let_result_raw_world_on e x w).
Proof.
  intros Hfresh Hresult. constructor.
  - destruct (world_wf w) as [[σ Hσ] _].
    destruct (Hresult σ Hσ) as [vx Hsteps].
    exists (<[x := vx]> σ). exists σ, vx. repeat split; eauto.
  - intros σx [σ [vx [Hσ [Hsteps ->]]]].
    rewrite dom_insert_L.
    rewrite (wfworld_store_dom w σ Hσ).
    set_solver.
Qed.

Definition let_result_world_on
    (e : tm) (x : atom) (w : WfWorld)
    (Hfresh : x ∉ world_dom (w : World))
    (Hresult : ∀ σ, (w : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e)) e →* tret vx)
    : WfWorld :=
  exist _ (let_result_raw_world_on e x w)
    (let_result_raw_world_on_wf e x w Hfresh Hresult).

Lemma let_result_world_on_dom e x (w : WfWorld) Hfresh Hresult :
  world_dom (let_result_world_on e x w Hfresh Hresult : World) =
  world_dom (w : World) ∪ {[x]}.
Proof. reflexivity. Qed.

Lemma let_result_world_on_member e x (w : WfWorld) Hfresh Hresult σ vx :
  (w : World) σ →
  subst_map (store_restrict σ (fv_tm e)) e →* tret vx →
  (let_result_world_on e x w Hfresh Hresult : World) (<[x := vx]> σ).
Proof.
  intros Hσ Hsteps. exists σ, vx. repeat split; eauto.
Qed.

Lemma let_result_world_on_elim e x (w : WfWorld) Hfresh Hresult σx :
  (let_result_world_on e x w Hfresh Hresult : World) σx →
  ∃ σ vx,
    (w : World) σ ∧
    subst_map (store_restrict σ (fv_tm e)) e →* tret vx ∧
    σx = <[x := vx]> σ.
Proof. intros Hσx. exact Hσx. Qed.

Lemma let_result_world_on_restrict e x (w : WfWorld) Hfresh Hresult :
  res_restrict (let_result_world_on e x w Hfresh Hresult)
    (world_dom (w : World)) = w.
Proof.
  apply wfworld_ext. apply world_ext.
  - simpl. set_solver.
  - intros σ. simpl. split.
    + intros [σx [[σ0 [vx [Hσ0 [Hsteps ->]]]] Hrestrict]].
      rewrite store_restrict_insert_notin in Hrestrict by exact Hfresh.
      assert (Hid : store_restrict σ0 (world_dom (w : World)) = σ0).
      { apply store_restrict_idemp. resource_solver. }
      rewrite Hid in Hrestrict.
      subst. exact Hσ0.
    + intros Hσ.
      destruct (Hresult σ Hσ) as [vx Hsteps].
      exists (<[x := vx]> σ). split.
      * exists σ, vx. repeat split; eauto.
      * rewrite store_restrict_insert_notin by exact Hfresh.
        apply store_restrict_idemp.
        resource_solver.
Qed.

Lemma let_result_world_on_restrict_old
    e x (w : WfWorld) Hfresh Hresult S :
  S ⊆ world_dom (w : World) →
  x ∉ S →
  res_restrict (let_result_world_on e x w Hfresh Hresult) S =
  res_restrict w S.
Proof.
  intros HSw HxS.
  apply wfworld_ext. apply world_ext.
  - simpl. set_solver.
  - intros σ. simpl. split.
    + intros [σx [[σ0 [vx [Hσ0 [Hsteps ->]]]] Hrestrict]].
      rewrite store_restrict_insert_notin in Hrestrict by exact HxS.
      exists σ0. split; [exact Hσ0 | exact Hrestrict].
    + intros [σ0 [Hσ0 Hrestrict]].
      destruct (Hresult σ0 Hσ0) as [vx Hsteps].
      exists (<[x := vx]> σ0). split.
      * exists σ0, vx. repeat split; eauto.
      * rewrite store_restrict_insert_notin by exact HxS.
        exact Hrestrict.
Qed.

Lemma let_result_world_on_restrict_input
    X e x (w : WfWorld) Hfresh Hresult Hfresh' Hresult' :
  fv_tm e ⊆ X →
  X ⊆ world_dom (w : World) →
  x ∉ X →
  res_restrict (let_result_world_on e x w Hfresh Hresult) (X ∪ {[x]}) =
  let_result_world_on e x (res_restrict w X) Hfresh' Hresult'.
Proof.
  intros Hfv HXw HxX.
  apply wfworld_ext. apply world_ext.
  - simpl. set_solver.
  - intros σx. simpl. split.
    + intros [σfull [[σ [vx [Hσ [Hsteps ->]]]] Hrestrict]].
      exists (store_restrict σ X), vx. split.
      * exists σ. split; [exact Hσ | reflexivity].
      * split.
        -- rewrite store_restrict_restrict.
           replace (X ∩ fv_tm e) with (fv_tm e) by set_solver.
           exact Hsteps.
        -- rewrite <- Hrestrict.
           rewrite store_restrict_insert_fresh_union.
           ++ reflexivity.
           ++ eapply store_lookup_none_of_dom.
              ** apply wfworld_store_dom. exact Hσ.
              ** exact Hfresh.
           ++ exact HxX.
    + intros [σ [vx [[σ0 [Hσ0 Hσ0X]] [Hsteps ->]]]].
      exists (<[x := vx]> σ0). split.
      * exists σ0, vx. split; [exact Hσ0 |]. split.
        -- rewrite <- Hσ0X in Hsteps.
           rewrite store_restrict_restrict in Hsteps.
           replace (X ∩ fv_tm e) with (fv_tm e) in Hsteps by set_solver.
           exact Hsteps.
        -- reflexivity.
      * rewrite store_restrict_insert_fresh_union.
        -- rewrite Hσ0X. reflexivity.
        -- eapply store_lookup_none_of_dom.
           ++ apply wfworld_store_dom. exact Hσ0.
           ++ exact Hfresh.
        -- exact HxX.
Qed.

Lemma let_result_world_on_restrict_input_le
    X e x (m n : WfWorld)
    Hfresh_m Hresult_m Hfresh_nX Hresult_nX :
  X ⊆ world_dom (m : World) →
  m ⊑ n →
  x ∉ X →
  fv_tm e ⊆ X →
  res_restrict (let_result_world_on e x m Hfresh_m Hresult_m) (X ∪ {[x]}) =
  let_result_world_on e x (res_restrict n X) Hfresh_nX Hresult_nX.
Proof.
  intros HXm Hle HxX Hfv.
  assert (Hfresh_mX : x ∉ world_dom (res_restrict m X : World)).
  { simpl. set_solver. }
  assert (Hresult_mX :
    ∀ σ, (res_restrict m X : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e)) e →* tret vx).
  {
    intros σ Hσ.
    destruct Hσ as [σm [Hσm Hrestrict]].
    destruct (Hresult_m σm Hσm) as [vx Hsteps].
    exists vx.
    rewrite <- Hrestrict.
    rewrite store_restrict_restrict.
    replace (X ∩ fv_tm e) with (fv_tm e) by set_solver.
    exact Hsteps.
  }
  rewrite (let_result_world_on_restrict_input
    X e x m Hfresh_m Hresult_m Hfresh_mX Hresult_mX Hfv HXm HxX).
  assert (Hbase : res_restrict m X = res_restrict n X).
  { apply res_restrict_le_eq; [exact Hle | exact HXm]. }
  destruct Hbase.
  apply wfworld_ext. apply world_ext.
  - reflexivity.
  - intros σx. simpl. split; intros Hσx; exact Hσx.
Qed.

Lemma let_result_world_on_restrict_domain
    X e x (w : WfWorld) Hfresh Hresult :
  world_dom (w : World) = X →
  res_restrict (let_result_world_on e x w Hfresh Hresult) (X ∪ {[x]}) =
  let_result_world_on e x w Hfresh Hresult.
Proof.
  intros Hdomw.
  replace (X ∪ {[x]}) with
    (world_dom (let_result_world_on e x w Hfresh Hresult : World)).
  - apply wfworld_ext. apply world_ext.
    + simpl. set_solver.
    + intros σx. simpl. split.
      * intros [σfull [Hσfull Hrestrict]].
        rewrite store_restrict_idemp in Hrestrict.
        -- subst σx. exact Hσfull.
        -- pose proof (wfworld_store_dom
             (let_result_world_on e x w Hfresh Hresult) σfull Hσfull) as Hdomσ.
           set_solver.
      * intros Hσx.
        exists σx. split; [exact Hσx |].
        apply store_restrict_idemp.
        pose proof (wfworld_store_dom
          (let_result_world_on e x w Hfresh Hresult) σx Hσx) as Hdomσ.
        set_solver.
  - rewrite let_result_world_on_dom, Hdomw. reflexivity.
Qed.

Lemma let_result_world_on_le e x (w : WfWorld) Hfresh Hresult :
  w ⊑ let_result_world_on e x w Hfresh Hresult.
Proof.
  pose proof (res_restrict_le
    (let_result_world_on e x w Hfresh Hresult)
    (world_dom (w : World))) as Hle.
  rewrite (let_result_world_on_restrict e x w Hfresh Hresult) in Hle.
  exact Hle.
Qed.

Lemma let_result_world_on_tlete_decompose :
  ∀ X e1 e2 x ν (n : WfWorld)
    Hfreshx Hresult1 Hfreshν Hresult2 Hfreshν_tlet Hresult_tlet,
    fv_tm (tlete e1 e2) ⊆ X →
    x ∉ X ∪ fv_tm e2 ∪ {[ν]} →
    ν ∉ world_dom (n : World) →
    X ⊆ world_dom (n : World) →
    (∀ σ, (n : World) σ → closed_env (store_restrict σ X)) →
    (∀ σ, (n : World) σ → lc_env (store_restrict σ X)) →
    (∀ σ vx,
      (n : World) σ →
      subst_map (store_restrict σ X) e1 →* tret vx →
      stale vx = ∅ ∧ is_lc vx) →
    (∀ σ, (n : World) σ → body_tm (subst_map (store_restrict σ X) e2)) →
    res_restrict
      (let_result_world_on (e2 ^^ x) ν
        (let_result_world_on e1 x n Hfreshx Hresult1)
        Hfreshν Hresult2)
      (world_dom (n : World) ∪ {[ν]}) =
    let_result_world_on (tlete e1 e2) ν n Hfreshν_tlet Hresult_tlet.
Proof.
Admitted.
