(** * ChoiceTyping.LetResultWorld

    Resource worlds generated by evaluating an expression into a fresh result
    coordinate.  These lemmas keep the operational/result-world bookkeeping out
    of the main soundness helper file. *)

From CoreLang Require Import Instantiation InstantiationProps LocallyNamelessProps
  OperationalProps.
From ChoiceTyping Require Export Typing.

Definition let_result_raw_world_on
    (X : aset) (e : tm) (x : atom) (w : WfWorld) : World := {|
  world_dom := world_dom (w : World) ∪ {[x]};
  world_stores := fun σx =>
    ∃ σ vx,
      (w : World) σ ∧
      subst_map (store_restrict σ X) e →* tret vx ∧
      σx = <[x := vx]> σ;
|}.

Lemma let_result_raw_world_on_wf X e x (w : WfWorld) :
  x ∉ world_dom (w : World) →
  (∀ σ, (w : World) σ → ∃ vx, subst_map (store_restrict σ X) e →* tret vx) →
  wf_world (let_result_raw_world_on X e x w).
Proof.
  intros Hfresh Hresult. constructor.
  - destruct (world_wf w) as [[σ Hσ] _].
    destruct (Hresult σ Hσ) as [vx Hsteps].
    exists (<[x := vx]> σ). exists σ, vx. repeat split; eauto.
  - intros σx [σ [vx [Hσ [Hsteps ->]]]].
    rewrite dom_insert_L.
    rewrite (wfworld_store_dom w σ Hσ).
    set_solver.
Qed.

Definition let_result_world_on
    (X : aset) (e : tm) (x : atom) (w : WfWorld)
    (Hfresh : x ∉ world_dom (w : World))
    (Hresult : ∀ σ, (w : World) σ → ∃ vx, subst_map (store_restrict σ X) e →* tret vx)
    : WfWorld :=
  exist _ (let_result_raw_world_on X e x w)
    (let_result_raw_world_on_wf X e x w Hfresh Hresult).

Lemma let_result_world_on_member X e x (w : WfWorld) Hfresh Hresult σ vx :
  (w : World) σ →
  subst_map (store_restrict σ X) e →* tret vx →
  (let_result_world_on X e x w Hfresh Hresult : World) (<[x := vx]> σ).
Proof.
  intros Hσ Hsteps. exists σ, vx. repeat split; eauto.
Qed.

Lemma let_result_world_on_elim X e x (w : WfWorld) Hfresh Hresult σx :
  (let_result_world_on X e x w Hfresh Hresult : World) σx →
  ∃ σ vx,
    (w : World) σ ∧
    subst_map (store_restrict σ X) e →* tret vx ∧
    σx = <[x := vx]> σ.
Proof. intros Hσx. exact Hσx. Qed.

Lemma let_result_world_on_restrict X e x (w : WfWorld) Hfresh Hresult :
  res_restrict (let_result_world_on X e x w Hfresh Hresult)
    (world_dom (w : World)) = w.
Proof.
  apply wfworld_ext. apply world_ext.
  - simpl. set_solver.
  - intros σ. simpl. split.
    + intros [σx [[σ0 [vx [Hσ0 [Hsteps ->]]]] Hrestrict]].
      rewrite store_restrict_insert_notin in Hrestrict by exact Hfresh.
      assert (Hid : store_restrict σ0 (world_dom (w : World)) = σ0).
      { apply store_restrict_idemp.
        pose proof (wfworld_store_dom w σ0 Hσ0). set_solver. }
      rewrite Hid in Hrestrict.
      subst. exact Hσ0.
    + intros Hσ.
      destruct (Hresult σ Hσ) as [vx Hsteps].
      exists (<[x := vx]> σ). split.
      * exists σ, vx. repeat split; eauto.
      * rewrite store_restrict_insert_notin by exact Hfresh.
        apply store_restrict_idemp.
        pose proof (wfworld_store_dom w σ Hσ). set_solver.
Qed.

Lemma let_result_world_on_restrict_old
    X e x (w : WfWorld) Hfresh Hresult S :
  S ⊆ world_dom (w : World) →
  x ∉ S →
  res_restrict (let_result_world_on X e x w Hfresh Hresult) S =
  res_restrict w S.
Proof.
  intros HSw HxS.
  apply wfworld_ext. apply world_ext.
  - simpl. set_solver.
  - intros σ. simpl. split.
    + intros [σx [[σ0 [vx [Hσ0 [Hsteps ->]]]] Hrestrict]].
      rewrite store_restrict_insert_notin in Hrestrict by exact HxS.
      exists σ0. split; [exact Hσ0 | exact Hrestrict].
    + intros [σ0 [Hσ0 Hrestrict]].
      destruct (Hresult σ0 Hσ0) as [vx Hsteps].
      exists (<[x := vx]> σ0). split.
      * exists σ0, vx. repeat split; eauto.
      * rewrite store_restrict_insert_notin by exact HxS.
        exact Hrestrict.
Qed.

Lemma let_result_world_on_le X e x (w : WfWorld) Hfresh Hresult :
  w ⊑ let_result_world_on X e x w Hfresh Hresult.
Proof.
  pose proof (res_restrict_le
    (let_result_world_on X e x w Hfresh Hresult)
    (world_dom (w : World))) as Hle.
  rewrite (let_result_world_on_restrict X e x w Hfresh Hresult) in Hle.
  exact Hle.
Qed.

Lemma store_restrict_insert_fresh_union_for_let_result
    (σ : Store) (X : aset) (x : atom) (v : value) :
  σ !! x = None →
  x ∉ X →
  store_restrict (<[x := v]> σ) (X ∪ {[x]}) =
  <[x := v]> (store_restrict σ X).
Proof.
  intros Hx_none HxX.
  rewrite store_restrict_insert_in by set_solver.
  f_equal.
  apply (map_eq (M := gmap atom)). intros z.
  change ((store_restrict σ (X ∪ {[x]}) : Store) !! z =
    (store_restrict σ X : Store) !! z).
  rewrite (@store_restrict_lookup value σ (X ∪ {[x]}) z) at 1.
  rewrite (@store_restrict_lookup value σ X z) at 1.
  destruct (decide (z = x)) as [->|Hzx].
  - rewrite decide_True by set_solver.
    rewrite decide_False by exact HxX.
    exact Hx_none.
  - destruct (decide (z ∈ X)) as [HzX|HzX].
    + rewrite !decide_True by set_solver. reflexivity.
    + rewrite !decide_False by set_solver. reflexivity.
Qed.

Lemma let_result_world_on_tlete_decompose :
  ∀ X e1 e2 x ν (n : WfWorld)
    Hfreshx Hresult1 Hfreshν Hresult2 Hfreshν_tlet Hresult_tlet,
    fv_tm (tlete e1 e2) ⊆ X →
    x ∉ X ∪ fv_tm e2 ∪ {[ν]} →
    ν ∉ world_dom (n : World) →
    X ⊆ world_dom (n : World) →
    (∀ σ, (n : World) σ → closed_env (store_restrict σ X)) →
    (∀ σ, (n : World) σ → lc_env (store_restrict σ X)) →
    (∀ σ vx,
      (n : World) σ →
      subst_map (store_restrict σ X) e1 →* tret vx →
      stale vx = ∅ ∧ is_lc vx) →
    (∀ σ, (n : World) σ → body_tm (subst_map (store_restrict σ X) e2)) →
    res_restrict
      (let_result_world_on (X ∪ {[x]}) (e2 ^^ x) ν
        (let_result_world_on X e1 x n Hfreshx Hresult1)
        Hfreshν Hresult2)
      (world_dom (n : World) ∪ {[ν]}) =
    let_result_world_on X (tlete e1 e2) ν n Hfreshν_tlet Hresult_tlet.
Proof.
  intros X e1 e2 x ν n Hfreshx Hresult1 Hfreshν Hresult2
    Hfreshν_tlet Hresult_tlet Hfv Hx Hνn HXn Hclosed Hlc Hres_regular Hbody.
  apply wfworld_ext. apply world_ext.
  - simpl. set_solver.
  - intros τstore. simpl. split.
    + intros [σfull [Hw2 Hrestrict]].
      destruct (let_result_world_on_elim
        (X ∪ {[x]}) (e2 ^^ x) ν
        (let_result_world_on X e1 x n Hfreshx Hresult1)
        Hfreshν Hresult2 σfull Hw2)
        as [σx [v [Hσx [Hsteps_body ->]]]].
      destruct (let_result_world_on_elim X e1 x n Hfreshx Hresult1 σx Hσx)
        as [σ [vx [Hσ [Hsteps1 ->]]]].
      exists σ, v. repeat split; try exact Hσ.
      * change (subst_map (store_restrict σ X) (tlete e1 e2))
          with (m{store_restrict σ X} (tlete e1 e2)).
        rewrite msubst_lete.
        eapply reduction_lete_intro.
        -- apply Hbody. exact Hσ.
        -- exact Hsteps1.
        -- rewrite store_restrict_insert_fresh_union_for_let_result in Hsteps_body.
           2:{
             apply not_elem_of_dom.
             pose proof (wfworld_store_dom n σ Hσ) as Hdomσ.
             rewrite Hdomσ. exact Hfreshx.
           }
           2:{ set_solver. }
           change (m{<[x := vx]> (store_restrict σ X)}
             (open_tm 0 (vfvar x) e2) →* tret v) in Hsteps_body.
           rewrite <- (msubst_intro_open_tm e2 0 vx x (store_restrict σ X)).
           ++ exact Hsteps_body.
           ++ apply Hclosed. exact Hσ.
           ++ apply (proj1 (Hres_regular σ vx Hσ Hsteps1)).
           ++ apply (proj2 (Hres_regular σ vx Hσ Hsteps1)).
           ++ apply Hlc. exact Hσ.
           ++ change (x ∉ dom (store_restrict σ X) ∪ fv_tm e2).
              rewrite store_restrict_dom. set_solver.
      * rewrite <- Hrestrict.
        rewrite insert_insert_ne by set_solver.
        rewrite store_restrict_insert_notin by set_solver.
        apply store_restrict_idemp.
        change (dom (<[ν := v]> σ : Store) ⊆ world_dom (n : World) ∪ {[ν]}).
        rewrite dom_insert_L.
        pose proof (wfworld_store_dom n σ Hσ) as Hdomσ.
        rewrite Hdomσ. set_solver.
    + intros [σ [v [Hσ [Hsteps_tlet ->]]]].
      change (subst_map (store_restrict σ X) (tlete e1 e2))
        with (m{store_restrict σ X} (tlete e1 e2)) in Hsteps_tlet.
      rewrite msubst_lete in Hsteps_tlet.
      destruct (reduction_lete
        (m{store_restrict σ X} e1) (m{store_restrict σ X} e2) v
        Hsteps_tlet) as [vx [Hsteps1 Hsteps2]].
      exists (<[ν := v]> (<[x := vx]> σ)). split.
      * apply (let_result_world_on_member
          (X ∪ {[x]}) (e2 ^^ x) ν
          (let_result_world_on X e1 x n Hfreshx Hresult1)
          Hfreshν Hresult2 (<[x := vx]> σ) v).
        -- apply let_result_world_on_member; [exact Hσ | exact Hsteps1].
        -- rewrite store_restrict_insert_fresh_union_for_let_result.
           2:{
             apply not_elem_of_dom.
             pose proof (wfworld_store_dom n σ Hσ) as Hdomσ.
             rewrite Hdomσ. exact Hfreshx.
           }
           2:{ set_solver. }
           replace (subst_map (<[x := vx]> (store_restrict σ X)) (e2 ^^ x))
             with (open_tm 0 vx (subst_map (store_restrict σ X) e2)).
           ++ exact Hsteps2.
           ++ change (e2 ^^ x) with (open_tm 0 (vfvar x) e2).
              symmetry. apply (msubst_intro_open_tm e2 0 vx x (store_restrict σ X)).
              ** apply Hclosed. exact Hσ.
              ** apply (proj1 (Hres_regular σ vx Hσ Hsteps1)).
              ** apply (proj2 (Hres_regular σ vx Hσ Hsteps1)).
              ** apply Hlc. exact Hσ.
              ** change (x ∉ dom (store_restrict σ X) ∪ fv_tm e2).
                 rewrite store_restrict_dom. set_solver.
      * rewrite insert_insert_ne by set_solver.
        rewrite store_restrict_insert_notin by set_solver.
        apply store_restrict_idemp.
        change (dom (<[ν := v]> σ : Store) ⊆ world_dom (n : World) ∪ {[ν]}).
        rewrite dom_insert_L.
        pose proof (wfworld_store_dom n σ Hσ) as Hdomσ.
        rewrite Hdomσ. set_solver.
Qed.
