(** * ChoiceTyping.TLetDenotation

    Thin denotation-level interface for the [tlet] soundness case. *)

From CoreLang Require Import Instantiation InstantiationProps OperationalProps BasicTypingProps
  LocallyNamelessProps StrongNormalization Sugar.
From ChoiceTyping Require Export TLetTotal RegularDenotation.
From ChoiceTyping Require Import Naming ResultWorldBridge ResultWorldFreshForall.
From ChoiceType Require Import BasicStore LocallyNamelessProps.

Import Tactics.

Lemma choice_typing_wf_from_erased_denot_ctx_basic_ty Σ Γ e τ m :
  basic_ctx (dom Σ) Γ →
  basic_choice_ty (dom (erase_ctx_under Σ Γ)) τ →
  m ⊨ denot_ctx_in_env Σ Γ →
  erase_ctx_under Σ Γ ⊢ₑ e ⋮ erase_ty τ →
  choice_typing_wf Σ Γ e τ.
Proof.
  intros Hctx Hτ Hm Herase.
  split; [| exact Herase].
  split.
  - split; [exact Hctx | exists m; exact Hm].
  - rewrite <- (erase_ctx_under_dom_basic Σ Γ Hctx).
    exact Hτ.
Qed.

Lemma denot_ty_total_model_choice_typing_wf Σ Γ e τ m :
  erase_ctx_under Σ Γ ⊢ₑ e ⋮ erase_ty τ →
  m ⊨ denot_ctx_in_env Σ Γ →
  denot_ty_total_model_in_ctx_under Σ Γ τ e m →
  choice_typing_wf Σ Γ e τ.
Proof.
  intros Herase Hm Hmodel.
  eapply choice_typing_wf_from_erased_denot_ctx_basic_ty; eauto.
  - exact (denot_ty_total_model_basic_ctx Σ Γ τ e m Hmodel).
  - exact (denot_ty_total_model_basic_choice_ty Σ Γ τ e m Hmodel).
Qed.

Lemma tlet_split_premises_choice_typing_wf_e1
    (Σ : gmap atom ty) (Γ : ctx) (τ1 : choice_ty) e1
    (m : WfWorld) :
  erase_ctx_under Σ Γ ⊢ₑ e1 ⋮ erase_ty τ1 →
  m ⊨ denot_ctx_in_env Σ Γ →
  denot_ty_total_model_in_ctx_under Σ Γ τ1 e1 m →
  choice_typing_wf Σ Γ e1 τ1.
Proof.
  intros Herase Hm Hmodel.
  eapply denot_ty_total_model_choice_typing_wf; eauto.
Qed.

Lemma tlet_split_premises_body_ctx_from_result
    (Σ : gmap atom ty) (Γ : ctx) (τ1 : choice_ty) e1 x
    (m : WfWorld)
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx) :
  erase_ctx_under Σ Γ ⊢ₑ e1 ⋮ erase_ty τ1 →
  m ⊨ denot_ctx_in_env Σ Γ →
  denot_ty_total_model_in_ctx_under Σ Γ τ1 e1 m →
  let_result_world_on e1 x m Hfresh Hresult ⊨
    denot_ctx_in_env Σ (CtxComma Γ (CtxBind x τ1)).
Proof.
  intros Herase Hm Hmodel.
  eapply let_result_world_on_denot_ctx_in_env.
  - eapply tlet_split_premises_choice_typing_wf_e1; eauto.
  - exact Hm.
  - exact (denot_ty_total_model_formula Σ Γ τ1 e1 m Hmodel).
  - eapply let_result_world_on_bound_fresh.
    + eapply tlet_split_premises_choice_typing_wf_e1; eauto.
    + exact Hm.
    + exact (denot_ty_total_model_total Σ Γ τ1 e1 m Hmodel).
    + exact Hfresh.
Qed.

Lemma denot_ctx_in_env_world_store_closed_on_erased Σ Γ m :
  basic_ctx (dom Σ) Γ →
  m ⊨ denot_ctx_in_env Σ Γ →
  world_store_closed_on (dom (erase_ctx_under Σ Γ)) m.
Proof.
  intros Hbasic Hctx σ Hσ.
  assert (Hdom_erase :
    dom (erase_ctx_under Σ Γ) = dom Σ ∪ ctx_dom Γ).
  { apply erase_ctx_under_dom_basic. exact Hbasic. }
  rewrite Hdom_erase.
  split.
  - exact (proj1 (denot_ctx_in_env_store_erased_typed
      Σ Γ m σ Hbasic Hctx Hσ)).
  - exact (denot_ctx_in_env_store_erased_lc
      Σ Γ m σ Hbasic Hctx Hσ).
Qed.

Lemma denot_ty_fuel_formula_fv_subset_env
    gas (Σ : gmap atom ty) (τ : choice_ty) e :
  cty_measure τ <= gas →
  fv_cty τ ⊆ dom Σ →
  formula_fv (denot_ty_fuel gas Σ τ e) ⊆ dom Σ.
Proof.
  intros Hgas Hfv.
  pose proof (denot_ty_fuel_formula_fv_subset gas Σ τ e Hgas) as Hφ.
  set_solver.
Qed.

Lemma world_store_closed_on_mono (X Y : aset) (m : WfWorld) :
  X ⊆ Y →
  world_store_closed_on Y m →
  world_store_closed_on X m.
Proof.
  intros HXY Hclosed σ Hσ.
  specialize (Hclosed σ Hσ) as [Hclosed_env Hlc_env].
  split.
  - replace (store_restrict σ X) with
      (store_restrict (store_restrict σ Y) X).
    + apply closed_env_restrict. exact Hclosed_env.
    + store_norm. replace (Y ∩ X) with X by set_solver. reflexivity.
  - replace (store_restrict σ X) with
      (store_restrict (store_restrict σ Y) X).
    + apply lc_env_restrict. exact Hlc_env.
    + store_norm. replace (Y ∩ X) with X by set_solver. reflexivity.
Qed.

(** ** Exact-domain bridge for expression-result continuations

    This is the stable version of the informal principle:

    [m ⊨ ∀ν. FExprResultOn (dom Σ) e ν ⇒ P ν]

    iff every sufficiently fresh concrete result world generated by evaluating
    [e] at [ν] satisfies [P ν].

    The exact-domain premise [world_dom m = dom Σ] is intentionally strong.
    [FExprResultOn (dom Σ) e ν] fibers over [dom Σ], while [let_result_world_on]
    extends the whole input world.  When the input world has exactly [dom Σ],
    these two views describe the same input fibers.  The basic typing premise
    [Σ ⊢ₑ e ⋮ T] supplies the usual regularity facts, in particular
    [fv_tm e ⊆ dom Σ] and [lc_tm e], so the statement does not carry those
    bookkeeping hypotheses separately. *)

Definition formula_family_rename_stable_on
    (D : aset) (P : atom → FormulaQ) : Prop :=
  ∀ x y n,
    x ∉ D →
    y ∉ D →
    n ⊨ formula_rename_atom x y (P x) ↔ n ⊨ P y.

Lemma FExprContIn_post_eq_at_fresh
    (Σ : gmap atom ty) e (P Q : atom → FormulaQ) :
  P (fresh_for (dom Σ)) = Q (fresh_for (dom Σ)) →
  FExprContIn Σ e P = FExprContIn Σ e Q.
Proof.
  intros Heq.
  unfold FExprContIn, fresh_forall.
  rewrite Heq. reflexivity.
Qed.

Lemma formula_rename_atom_fv_subset_pair D x y (φ : FormulaQ) :
  x ∉ D →
  y ∉ D →
  formula_fv φ ⊆ D ∪ {[x]} →
  formula_fv (formula_rename_atom x y φ) ⊆ D ∪ {[y]}.
Proof.
  intros HxD HyD Hfv.
  etrans.
  - apply formula_fv_rename_atom_subset_open.
    intros Hy.
    rewrite elem_of_difference in Hy.
    destruct Hy as [Hyφ Hyx].
    pose proof (Hfv _ Hyφ) as HyD_or_x.
    set_solver.
  - set_solver.
Qed.

Lemma denot_refinement_over_cont_insert_fresh_eq
    (D : aset) (Σ : gmap atom ty) x Tx b φ ν :
  x ∉ D ∪ qual_dom φ →
  dom Σ = D →
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> (<[x := Tx]> Σ))
       ({[ν]} ∪ qual_dom φν))
     (fib_vars (qual_dom φν)
       (FOver (FAtom (lift_type_qualifier_to_logic φν))))) =
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> Σ)
       ({[ν]} ∪ qual_dom φν))
     (fib_vars (qual_dom φν)
       (FOver (FAtom (lift_type_qualifier_to_logic φν))))).
Proof.
  intros Hx Hdom.
  f_equal.
  apply basic_world_formula_agree. intros z Hz.
  rewrite !lookup_insert.
  destruct (decide (z = ν)) as [->|Hzν].
  - rewrite !decide_True by reflexivity. reflexivity.
  - rewrite !decide_False by congruence.
    destruct (decide (z = x)) as [->|Hzx].
    + pose proof (qual_open_atom_dom_subset 0 ν φ x) as Hopen.
      assert (x ∈ qual_dom (qual_open_atom 0 ν φ)) by set_solver.
      pose proof (Hopen H) as Hxopen.
      set_solver.
    + repeat rewrite decide_False by congruence. reflexivity.
Qed.

Lemma denot_refinement_under_cont_insert_fresh_eq
    (D : aset) (Σ : gmap atom ty) x Tx b φ ν :
  x ∉ D ∪ qual_dom φ →
  dom Σ = D →
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> (<[x := Tx]> Σ))
       ({[ν]} ∪ qual_dom φν))
     (fib_vars (qual_dom φν)
       (FUnder (FAtom (lift_type_qualifier_to_logic φν))))) =
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> Σ)
       ({[ν]} ∪ qual_dom φν))
     (fib_vars (qual_dom φν)
       (FUnder (FAtom (lift_type_qualifier_to_logic φν))))).
Proof.
  intros Hx Hdom.
  f_equal.
  apply basic_world_formula_agree. intros z Hz.
  rewrite !lookup_insert.
  destruct (decide (z = ν)) as [->|Hzν].
  - rewrite !decide_True by reflexivity. reflexivity.
  - rewrite !decide_False by congruence.
    destruct (decide (z = x)) as [->|Hzx].
    + pose proof (qual_open_atom_dom_subset 0 ν φ x) as Hopen.
      assert (x ∈ qual_dom (qual_open_atom 0 ν φ)) by set_solver.
      pose proof (Hopen H) as Hxopen.
      set_solver.
    + repeat rewrite decide_False by congruence. reflexivity.
Qed.

(** The refinement continuations generated by [CTOver]/[CTUnder] mention only
    the ambient erased environment, the opened result coordinate, and the free
    variables recorded by the qualifier metadata.  This is the fv half of the
    hypothesis needed by [FExprCont_tlet_reduction]. *)
Lemma denot_refinement_over_cont_fv_subset
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  ∀ ν,
    formula_fv
      (let φν := qual_open_atom 0 ν φ in
       FAnd
         (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
         (fib_vars (qual_dom φν)
           (FOver (FAtom (lift_type_qualifier_to_logic φν))))) ⊆
    D ∪ {[ν]}.
Proof.
  intros Hφ ν.
  cbn [formula_fv].
  rewrite basic_world_formula_fv.
  rewrite fib_vars_formula_fv.
  cbn [formula_fv].
  unfold stale, stale_logic_qualifier.
  rewrite lqual_dom_lift_type_qualifier_to_logic.
  pose proof (qual_open_atom_dom_subset 0 ν φ) as Hopen.
  set_solver.
Qed.

Lemma denot_refinement_under_cont_fv_subset
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  ∀ ν,
    formula_fv
      (let φν := qual_open_atom 0 ν φ in
       FAnd
         (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
         (fib_vars (qual_dom φν)
           (FUnder (FAtom (lift_type_qualifier_to_logic φν))))) ⊆
    D ∪ {[ν]}.
Proof.
  intros Hφ ν.
  cbn [formula_fv].
  rewrite basic_world_formula_fv.
  rewrite fib_vars_formula_fv.
  cbn [formula_fv].
  unfold stale, stale_logic_qualifier.
  rewrite lqual_dom_lift_type_qualifier_to_logic.
  pose proof (qual_open_atom_dom_subset 0 ν φ) as Hopen.
  set_solver.
Qed.

Lemma qual_open_atom_dom_eq_member k x q :
  k ∈ qual_bvars q →
  qual_dom (qual_open_atom k x q) = {[x]} ∪ qual_dom q.
Proof.
  destruct q as [B d p]. unfold qual_open_atom, qual_bvars, qual_dom.
  simpl. intros Hk. rewrite decide_True by exact Hk. reflexivity.
Qed.

Lemma qual_open_atom_eq_not_member k x q :
  k ∉ qual_bvars q →
  qual_open_atom k x q = q.
Proof.
  destruct q as [B d p]. unfold qual_open_atom, qual_bvars.
  simpl. intros Hk. rewrite decide_False by exact Hk. reflexivity.
Qed.

Lemma qual_open_atom_dom_union_singleton k x q :
  {[x]} ∪ qual_dom (qual_open_atom k x q) = {[x]} ∪ qual_dom q.
Proof.
  destruct q as [B d p]. unfold qual_open_atom, qual_dom, qual_bvars.
  simpl. destruct (decide (k ∈ B)); set_solver.
Qed.

Lemma formula_store_equiv_lift_open_over_rename_fresh k x y q :
  k ∈ qual_bvars q →
  x ∉ qual_dom q →
  y ∉ qual_dom q →
  formula_store_equiv
    (formula_rename_atom x y
      (FOver (FAtom (lift_type_qualifier_to_logic (qual_open_atom k x q)))))
    (FOver (FAtom (lift_type_qualifier_to_logic (qual_open_atom k y q)))).
Proof.
  intros Hk Hx Hy.
  destruct q as [B d p]. simpl in *.
  apply formula_store_equiv_over.
  - unfold formula_rename_atom, formula_swap. simpl.
    unfold stale, stale_logic_qualifier, lqual_dom, lqual_swap,
      lift_type_qualifier_to_logic, qual_open_atom.
    simpl. rewrite !decide_True by exact Hk.
    rewrite aset_swap_union, aset_swap_singleton.
    replace (atom_swap x y x) with y
      by (unfold atom_swap; repeat destruct decide; congruence).
    rewrite aset_swap_fresh by assumption.
    reflexivity.
  - intros ρ m.
    change (res_models_with_store ρ m
      (formula_rename_atom x y
        (FAtom (lift_type_qualifier_to_logic
          (qual_open_atom k x (qual B d p))))) ↔
      res_models_with_store ρ m
        (FAtom (lift_type_qualifier_to_logic
          (qual_open_atom k y (qual B d p))))).
    apply res_models_with_store_lift_open_rename_fresh; assumption.
Qed.

Lemma formula_store_equiv_lift_open_under_rename_fresh k x y q :
  k ∈ qual_bvars q →
  x ∉ qual_dom q →
  y ∉ qual_dom q →
  formula_store_equiv
    (formula_rename_atom x y
      (FUnder (FAtom (lift_type_qualifier_to_logic (qual_open_atom k x q)))))
    (FUnder (FAtom (lift_type_qualifier_to_logic (qual_open_atom k y q)))).
Proof.
  intros Hk Hx Hy.
  destruct q as [B d p]. simpl in *.
  apply formula_store_equiv_under.
  - unfold formula_rename_atom, formula_swap. simpl.
    unfold stale, stale_logic_qualifier, lqual_dom, lqual_swap,
      lift_type_qualifier_to_logic, qual_open_atom.
    simpl. rewrite !decide_True by exact Hk.
    rewrite aset_swap_union, aset_swap_singleton.
    replace (atom_swap x y x) with y
      by (unfold atom_swap; repeat destruct decide; congruence).
    rewrite aset_swap_fresh by assumption.
    reflexivity.
  - intros ρ m.
    change (res_models_with_store ρ m
      (formula_rename_atom x y
        (FAtom (lift_type_qualifier_to_logic
          (qual_open_atom k x (qual B d p))))) ↔
      res_models_with_store ρ m
        (FAtom (lift_type_qualifier_to_logic
          (qual_open_atom k y (qual B d p))))).
    apply res_models_with_store_lift_open_rename_fresh; assumption.
Qed.

Lemma denot_refinement_over_fib_rename_stable
    (D : aset) φ :
  qual_dom φ ⊆ D →
  ∀ x y m,
    x ∉ D →
    y ∉ D →
    m ⊨ formula_rename_atom x y
      (let φx := qual_open_atom 0 x φ in
       fib_vars (qual_dom φx)
         (FOver (FAtom (lift_type_qualifier_to_logic φx)))) ↔
    m ⊨
      (let φy := qual_open_atom 0 y φ in
       fib_vars (qual_dom φy)
         (FOver (FAtom (lift_type_qualifier_to_logic φy)))).
Proof.
  intros Hdom x y m HxD HyD.
  change (m ⊨ formula_rename_atom x y
      (fib_vars (qual_dom (qual_open_atom 0 x φ))
        (FOver (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 x φ))))) ↔
    m ⊨
      (fib_vars (qual_dom (qual_open_atom 0 y φ))
        (FOver (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 y φ)))))).
  destruct (decide (0 ∈ qual_bvars φ)) as [Hk|Hk].
  - rewrite !qual_open_atom_dom_eq_member by exact Hk.
    set (base_x := FOver (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 x φ)))).
    set (base_y := FOver (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 y φ)))).
    transitivity (m ⊨ fib_vars ({[y]} ∪ qual_dom φ)
      (formula_rename_atom x y base_x)).
    + apply res_models_of_formula_store_equiv.
      subst base_x. apply fib_vars_insert_rename_store_equiv; set_solver.
    + apply res_models_of_formula_store_equiv.
      destruct (fib_vars_store_equiv ({[y]} ∪ qual_dom φ)
        (formula_rename_atom x y base_x) base_y) as [_ Heq].
      * subst base_x base_y.
        destruct φ as [B d p]. simpl in *.
        rewrite !decide_True by exact Hk.
        unfold stale, stale_logic_qualifier, lqual_dom, lqual_swap,
          lift_type_qualifier_to_logic.
        simpl.
        rewrite aset_swap_union, aset_swap_singleton.
        replace (atom_swap x y x) with y
          by (unfold atom_swap; repeat destruct decide; congruence).
        rewrite aset_swap_fresh by set_solver.
        reflexivity.
      * subst base_x base_y.
        apply formula_store_equiv_lift_open_over_rename_fresh; set_solver.
      * exact Heq.
  - rewrite !qual_open_atom_eq_not_member by exact Hk.
    apply res_models_rename_atom_fresh.
    + rewrite fib_vars_formula_fv. simpl.
      unfold stale, stale_logic_qualifier.
      rewrite lqual_dom_lift_type_qualifier_to_logic. set_solver.
    + rewrite fib_vars_formula_fv. simpl.
      unfold stale, stale_logic_qualifier.
      rewrite lqual_dom_lift_type_qualifier_to_logic. set_solver.
Qed.

Lemma denot_refinement_under_fib_rename_stable
    (D : aset) φ :
  qual_dom φ ⊆ D →
  ∀ x y m,
    x ∉ D →
    y ∉ D →
    m ⊨ formula_rename_atom x y
      (let φx := qual_open_atom 0 x φ in
       fib_vars (qual_dom φx)
         (FUnder (FAtom (lift_type_qualifier_to_logic φx)))) ↔
    m ⊨
      (let φy := qual_open_atom 0 y φ in
       fib_vars (qual_dom φy)
         (FUnder (FAtom (lift_type_qualifier_to_logic φy)))).
Proof.
  intros Hdom x y m HxD HyD.
  change (m ⊨ formula_rename_atom x y
      (fib_vars (qual_dom (qual_open_atom 0 x φ))
        (FUnder (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 x φ))))) ↔
    m ⊨
      (fib_vars (qual_dom (qual_open_atom 0 y φ))
        (FUnder (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 y φ)))))).
  destruct (decide (0 ∈ qual_bvars φ)) as [Hk|Hk].
  - rewrite !qual_open_atom_dom_eq_member by exact Hk.
    set (base_x := FUnder (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 x φ)))).
    set (base_y := FUnder (FAtom (lift_type_qualifier_to_logic (qual_open_atom 0 y φ)))).
    transitivity (m ⊨ fib_vars ({[y]} ∪ qual_dom φ)
      (formula_rename_atom x y base_x)).
    + apply res_models_of_formula_store_equiv.
      subst base_x. apply fib_vars_insert_rename_store_equiv; set_solver.
    + apply res_models_of_formula_store_equiv.
      destruct (fib_vars_store_equiv ({[y]} ∪ qual_dom φ)
        (formula_rename_atom x y base_x) base_y) as [_ Heq].
      * subst base_x base_y.
        destruct φ as [B d p]. simpl in *.
        rewrite !decide_True by exact Hk.
        unfold stale, stale_logic_qualifier, lqual_dom, lqual_swap,
          lift_type_qualifier_to_logic.
        simpl.
        rewrite aset_swap_union, aset_swap_singleton.
        replace (atom_swap x y x) with y
          by (unfold atom_swap; repeat destruct decide; congruence).
        rewrite aset_swap_fresh by set_solver.
        reflexivity.
      * subst base_x base_y.
        apply formula_store_equiv_lift_open_under_rename_fresh; set_solver.
      * exact Heq.
  - rewrite !qual_open_atom_eq_not_member by exact Hk.
    apply res_models_rename_atom_fresh.
    + rewrite fib_vars_formula_fv. simpl.
      unfold stale, stale_logic_qualifier.
      rewrite lqual_dom_lift_type_qualifier_to_logic. set_solver.
    + rewrite fib_vars_formula_fv. simpl.
      unfold stale, stale_logic_qualifier.
      rewrite lqual_dom_lift_type_qualifier_to_logic. set_solver.
Qed.

Lemma denot_refinement_over_cont_rename_stable
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  formula_family_rename_stable_on D (fun ν =>
    let φν := qual_open_atom 0 ν φ in
    FAnd
      (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
      (fib_vars (qual_dom φν)
        (FOver (FAtom (lift_type_qualifier_to_logic φν))))).
Proof.
  intros Hφ x y m HxD HyD.
  unfold formula_family_rename_stable_on.
  simpl.
  split; intros H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      apply (proj1 Hbasic).
      replace ({[x]} ∪ qual_dom φ) with
          ({[x]} ∪ qual_dom (qual_open_atom 0 x φ))
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply res_models_and_elim_l in H. exact H.
    + pose proof (denot_refinement_over_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj1 Hfib).
      apply res_models_and_elim_r in H. exact H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      replace ({[x]} ∪ qual_dom (qual_open_atom 0 x φ)) with
          ({[x]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply (proj2 Hbasic).
      apply res_models_and_elim_l in H.
      replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ) in H
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      exact H.
    + pose proof (denot_refinement_over_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj2 Hfib).
      apply res_models_and_elim_r in H. exact H.
Qed.

Lemma denot_refinement_under_cont_rename_stable
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  formula_family_rename_stable_on D (fun ν =>
    let φν := qual_open_atom 0 ν φ in
    FAnd
      (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
      (fib_vars (qual_dom φν)
        (FUnder (FAtom (lift_type_qualifier_to_logic φν))))).
Proof.
  intros Hφ x y m HxD HyD.
  unfold formula_family_rename_stable_on.
  simpl.
  split; intros H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      apply (proj1 Hbasic).
      replace ({[x]} ∪ qual_dom φ) with
          ({[x]} ∪ qual_dom (qual_open_atom 0 x φ))
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply res_models_and_elim_l in H. exact H.
    + pose proof (denot_refinement_under_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj1 Hfib).
      apply res_models_and_elim_r in H. exact H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      replace ({[x]} ∪ qual_dom (qual_open_atom 0 x φ)) with
          ({[x]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply (proj2 Hbasic).
      apply res_models_and_elim_l in H.
      replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ) in H
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      exact H.
    + pose proof (denot_refinement_under_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj2 Hfib).
      apply res_models_and_elim_r in H. exact H.
Qed.

(** Renaming the cofinite representative of an expression-result continuation
    only changes the result coordinate.  This is the formal version of the
    [HHH] step in the proof below. *)
Lemma FExprResultOn_dom_rename_from_current_exact_domain
    (Σ : gmap atom ty) (T : ty) e ν (n : WfWorld) :
  Σ ⊢ₑ e ⋮ T →
  ν ∉ dom Σ →
  world_dom (n : World) = dom Σ ∪ {[ν]} →
  n ⊨ FExprResultOn (dom Σ) e ν →
  n ⊨ formula_rename_atom (fresh_for (dom Σ)) ν
        (FExprResultOn (dom Σ) e (fresh_for (dom Σ))).
Proof.
  intros _ Hν _ Hmodel.
  cbn [dom].
  rewrite FExprResultOn_rename_result_fresh.
  - exact Hmodel.
  - apply fresh_for_not_in.
  - exact Hν.
Qed.

Lemma expr_total_on_to_fv_result X e (m : WfWorld) :
  world_store_closed_on X m →
  expr_total_on X e m →
  ∀ σ, (m : World) σ →
    ∃ vx, subst_map (store_restrict σ (fv_tm e)) e →* tret vx.
Proof.
  intros Hclosed [Hfv Htotal] σ Hσ.
  destruct (strongly_normalizing_reaches_result _ (Htotal σ Hσ)) as [vx Hsteps].
  exists vx.
  pose proof (subst_map_eq_on_fv e
    (store_restrict σ X)
    (store_restrict σ (fv_tm e))) as Heq.
  assert (Hclosed_fv :
    closed_env (store_restrict (store_restrict σ X) (fv_tm e))).
  {
    apply closed_env_restrict.
    exact (proj1 (Hclosed σ Hσ)).
  }
  specialize (Heq Hclosed_fv).
  assert (Hagree :
    store_restrict (store_restrict σ (fv_tm e)) (fv_tm e) =
    store_restrict (store_restrict σ X) (fv_tm e)).
  {
    store_norm.
    replace (X ∩ fv_tm e) with (fv_tm e) by set_solver.
    reflexivity.
  }
  specialize (Heq Hagree).
  change (subst_map (store_restrict σ (fv_tm e)) e →* tret vx).
  replace (subst_map (store_restrict σ (fv_tm e)) e)
    with (subst_map (store_restrict σ X) e) by (symmetry; exact Heq).
  exact Hsteps.
Qed.

Lemma store_restrict_empty_union_elements (σ : Store) (X : aset) :
  store_restrict ((∅ : Store) ∪ store_restrict σ (list_to_set (elements X) : aset)) X =
  store_restrict σ X.
Proof.
  rewrite map_empty_union.
  store_norm.
  replace ((list_to_set (elements X) : aset) ∩ X) with X.
  - reflexivity.
  - apply set_eq. intros z.
    rewrite elem_of_intersection, elem_of_list_to_set, elem_of_elements.
    set_solver.
Qed.

Lemma store_restrict_empty_union_elements_fv
    (σ τ : Store) (X F : aset) :
  F ⊆ X →
  store_restrict τ X = σ →
  store_restrict
    (store_restrict ((∅ : Store) ∪ store_restrict τ (list_to_set (elements X) : aset)) X)
    F =
  store_restrict σ F.
Proof.
  intros HFX HτX.
  rewrite store_restrict_empty_union_elements.
  rewrite HτX.
  store_norm.
  replace (X ∩ F) with F by set_solver.
  reflexivity.
Qed.

Lemma FExprResultOn_dom_exact_domain_eq_let_result_world_on
    (Σ : gmap atom ty) (T : ty) e ν (m n : WfWorld)
    (Hfresh : ν ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e)) e →* tret vx) :
  Σ ⊢ₑ e ⋮ T →
  world_dom (m : World) = dom Σ →
  world_store_closed_on (dom Σ) m →
  world_dom (n : World) = dom Σ ∪ {[ν]} →
  res_restrict n (dom Σ) = m →
  n ⊨ FExprResultOn (dom Σ) e ν →
  n = let_result_world_on e ν m Hfresh Hresult.
Proof.
  intros Hty Hdom Hclosed Hdomn Hrestr Hmodel.
  set (X := dom Σ).
  assert (HνX : ν ∉ X) by (subst X; rewrite <- Hdom; exact Hfresh).
  assert (Hfv : fv_tm e ⊆ X).
  { subst X. apply basic_typing_contains_fv_tm in Hty. exact Hty. }
  assert (Hlc : lc_tm e).
  { eapply typing_tm_lc; eauto. }
  set (E := (∅ : Store)).
  assert (Hmodel_fold :
    res_models_with_store E n
      (foldr FFib (FAtom (expr_logic_qual_on X e ν)) (elements X))).
  {
    subst E. unfold res_models, FExprResultOn in Hmodel.
    subst X.
    unfold fib_vars, fib_vars_acc, set_fold in Hmodel.
    cbn [compose] in Hmodel.
    rewrite foldr_fib_vars_acc_fst_bridge in Hmodel.
    exact Hmodel.
  }
  apply wfworld_ext. apply world_ext.
  - rewrite Hdomn, let_result_world_on_dom, Hdom. subst X. reflexivity.
  - intros σν. split.
    + intros Hσν.
      assert (Hσm : (m : World) (store_restrict σν X)).
      {
        rewrite <- Hrestr.
        exists σν. split; [exact Hσν | reflexivity].
      }
      pose proof (foldr_fib_expr_result_sound
        (elements X) X e ν E n σν (store_restrict σν {[ν]})
        (NoDup_elements X)
        ltac:(subst E; rewrite dom_empty_L; set_solver)
        Hmodel_fold Hσν ltac:(reflexivity)) as Hstore.
      match type of Hstore with
      | expr_result_store _ (subst_map (store_restrict ?R _) _) _ =>
          replace (store_restrict R X) with (store_restrict σν X) in Hstore
      end.
      2:{ subst E. symmetry. apply store_restrict_empty_union_elements. }
      destruct Hstore as [vx [Hνpart [Hstale [Hlc_vx Hsteps]]]].
      exists (store_restrict σν X), vx. split; [exact Hσm |].
      split.
      {
        set (σX := store_restrict σν X).
        set (ρfv := store_restrict σX (fv_tm e)).
        assert (Hclosed_fv : closed_env (store_restrict σX (fv_tm e))).
        {
          subst σX X.
          apply closed_env_restrict.
          destruct (Hclosed _ Hσm) as [Hcl _].
          replace (store_restrict (store_restrict σν (dom Σ)) (dom Σ))
            with (store_restrict σν (dom Σ)) in Hcl.
          - exact Hcl.
          - store_norm. reflexivity.
        }
        pose proof (subst_map_eq_on_fv e σX ρfv Hclosed_fv) as Heq.
        assert (Hagree :
          store_restrict ρfv (fv_tm e) = store_restrict σX (fv_tm e)).
        { subst ρfv. store_norm. reflexivity. }
        specialize (Heq Hagree).
        change (subst_map ρfv e = subst_map σX e) in Heq.
        change (subst_map ρfv e →* tret vx).
        rewrite Heq. exact Hsteps.
      }
      assert (Hid : store_restrict σν (X ∪ {[ν]}) = σν).
      {
        apply store_restrict_idemp.
        pose proof (wfworld_store_dom n σν Hσν) as Hdomσν.
        change (dom σν ⊆ X ∪ {[ν]}).
        rewrite Hdomσν, Hdomn. subst X. set_solver.
      }
      pose proof (store_restrict_union_singleton_insert_from_projection
        σν X ν vx HνX Hνpart) as Hunion.
      rewrite Hid in Hunion. exact Hunion.
    + intros [σ [vx [Hσm [Hsteps ->]]]].
      assert (HprojX : (res_restrict n X : World) σ).
      {
        subst X. rewrite Hrestr. exact Hσm.
      }
      destruct HprojX as [τ [Hτn HτX]].
      assert (Hclosed_vx : stale vx = ∅ ∧ is_lc vx).
      {
        eapply (steps_closed_result_of_restrict_world X e m σ vx).
        - subst X. rewrite <- Hdom. set_solver.
        - exact Hfv.
        - exact Hlc.
        - subst X. exact Hclosed.
        - subst X. simpl.
          exists σ. split; [exact Hσm |].
          apply store_restrict_idemp.
          pose proof (wfworld_store_dom m σ Hσm) as Hdomσ.
          change (dom σ ⊆ dom Σ).
          rewrite Hdomσ, Hdom. set_solver.
        - pose proof (subst_map_eq_on_fv e
            (store_restrict σ X) (store_restrict σ (fv_tm e))) as Heq.
          assert (Hclosed_fv : closed_env
            (store_restrict (store_restrict σ X) (fv_tm e))).
          {
            subst X.
            apply closed_env_restrict.
            destruct (Hclosed _ Hσm) as [Hcl _].
            exact Hcl.
          }
          specialize (Heq Hclosed_fv).
          assert (Hagree :
            store_restrict (store_restrict σ (fv_tm e)) (fv_tm e) =
            store_restrict (store_restrict σ X) (fv_tm e)).
          { store_norm. replace (X ∩ fv_tm e) with (fv_tm e) by set_solver.
            reflexivity. }
          specialize (Heq Hagree).
          change (subst_map (store_restrict σ (fv_tm e)) e =
                  subst_map (store_restrict σ X) e) in Heq.
          rewrite <- Heq. exact Hsteps.
      }
      assert (Henv_eq :
        store_restrict
          (store_restrict (E ∪ store_restrict τ (list_to_set (elements X) : aset)) X)
          (fv_tm e) =
        store_restrict σ (fv_tm e)).
      {
        subst E.
        eapply store_restrict_empty_union_elements_fv; eauto.
      }
      assert (Hclosed_env :
        closed_env
          (store_restrict
            (store_restrict (E ∪ store_restrict τ (list_to_set (elements X) : aset)) X)
            (fv_tm e))).
      {
        rewrite Henv_eq.
        subst X.
        replace (store_restrict σ (fv_tm e))
          with (store_restrict (store_restrict σ (dom Σ)) (fv_tm e)).
        - apply closed_env_restrict.
          exact (proj1 (Hclosed σ Hσm)).
        - store_norm. replace (dom Σ ∩ fv_tm e) with (fv_tm e) by set_solver.
          reflexivity.
      }
      assert (Hexpr_store :
        expr_result_store ν
          (subst_map
            (store_restrict
              (E ∪ store_restrict τ (list_to_set (elements X) : aset)) X)
            e)
          {[ν := vx]}).
      {
        exists vx. split; [reflexivity |]. repeat split.
        - exact (proj1 Hclosed_vx).
        - exact (proj2 Hclosed_vx).
          - pose proof (subst_map_eq_on_fv e
            (store_restrict σ (fv_tm e))
            (store_restrict
              (E ∪ store_restrict τ (list_to_set (elements X) : aset)) X))
            as Heq.
          assert (Hclosed_sigma_fv :
            closed_env (store_restrict (store_restrict σ (fv_tm e)) (fv_tm e))).
          {
            replace (store_restrict (store_restrict σ (fv_tm e)) (fv_tm e))
              with (store_restrict σ (fv_tm e)).
            - rewrite <- Henv_eq. exact Hclosed_env.
            - store_norm. reflexivity.
          }
          specialize (Heq Hclosed_sigma_fv).
          assert (Hagree :
            store_restrict
              (store_restrict (E ∪ store_restrict τ (list_to_set (elements X) : aset)) X)
              (fv_tm e) =
            store_restrict (store_restrict σ (fv_tm e)) (fv_tm e)).
          {
            rewrite Henv_eq. store_norm. reflexivity.
          }
          specialize (Heq Hagree).
          change (subst_map
            (store_restrict (E ∪ store_restrict τ (list_to_set (elements X) : aset)) X)
            e =
            subst_map (store_restrict σ (fv_tm e)) e) in Heq.
          rewrite Heq. exact Hsteps.
      }
      destruct (foldr_fib_expr_result_complete_paired
        (elements X) X e ν E n τ {[ν := vx]}
        (NoDup_elements X)
        ltac:(subst E; rewrite dom_empty_L; set_solver)
        Hmodel_fold Hτn Hexpr_store)
        as [τ' [Hτ'n [Hτ'X Hτ'ν]]].
      assert (Hτ'_eq : τ' = <[ν := vx]> σ).
      {
        assert (Hid : store_restrict τ' (X ∪ {[ν]}) = τ').
        {
          apply store_restrict_idemp.
          pose proof (wfworld_store_dom n τ' Hτ'n) as Hdomτ'.
          change (dom τ' ⊆ X ∪ {[ν]}).
          rewrite Hdomτ', Hdomn. subst X. set_solver.
        }
        pose proof (store_restrict_union_singleton_insert_from_projection
          τ' X ν vx HνX Hτ'ν) as Hunion.
        assert (Hτ'X_dom : store_restrict τ' X = store_restrict τ X).
        {
          replace X with (list_to_set (elements X) : aset).
          - exact Hτ'X.
          - apply set_eq. intros z.
            rewrite elem_of_list_to_set, elem_of_elements. reflexivity.
        }
        rewrite Hτ'X_dom, HτX in Hunion.
        rewrite Hid in Hunion. exact Hunion.
      }
      rewrite <- Hτ'_eq. exact Hτ'n.
Qed.

Lemma FExprContIn_to_let_result_world_on_exact_domain
    (Σ : gmap atom ty) (T : ty) e
    (P : atom → FormulaQ) (m : WfWorld) :
  Σ ⊢ₑ e ⋮ T →
  world_dom (m : World) = dom Σ →
  world_store_closed_on (dom Σ) m →
  expr_total_on (dom Σ) e m →
  (∀ ν, formula_fv (P ν) ⊆ dom Σ ∪ {[ν]}) →
  formula_family_rename_stable_on (dom Σ) P →
  m ⊨ FExprContIn Σ e P →
  ∃ L : aset,
    dom Σ ⊆ L ∧
    ∀ ν,
      ν ∉ L →
      ∀ Hfresh Hresult,
        let_result_world_on e ν m Hfresh Hresult ⊨ P ν.
Proof.
  intros Hty Hdom Hclosed Htotal HPfv HPrename Hcont.
  pose proof (basic_typing_contains_fv_tm _ _ _ Hty) as Hfv.
  pose proof (typing_tm_lc _ _ _ Hty) as Hlc.
  unfold FExprContIn in Hcont.
  destruct (fresh_forall_expr_result_to_let_result_world
    (dom Σ) e (dom Σ) P m Hfv Hlc
    ltac:(rewrite <- Hdom; set_solver) Hclosed Hcont)
    as [L [HL Huse]].
  exists (L ∪ dom Σ). split; [set_solver |].
  intros ν Hν Hfresh Hresult.
  eapply Huse.
  - set_solver.
  - intros n Hdomn Hn.
    cbn [dom].
    eapply FExprResultOn_dom_rename_from_current_exact_domain; eauto.
    + set_solver.
    + rewrite <- Hdom. exact Hdomn.
  - intros n Hn.
    apply (proj1 (HPrename (fresh_for (dom Σ)) ν n
      ltac:(apply fresh_for_not_in) ltac:(set_solver))).
    exact Hn.
Qed.

Lemma let_result_world_on_to_FExprContIn_exact_domain
    (Σ : gmap atom ty) (T : ty) e
    (P : atom → FormulaQ) (m : WfWorld) :
  Σ ⊢ₑ e ⋮ T →
  world_dom (m : World) = dom Σ →
  world_store_closed_on (dom Σ) m →
  expr_total_on (dom Σ) e m →
  (∀ ν, formula_fv (P ν) ⊆ dom Σ ∪ {[ν]}) →
  formula_family_rename_stable_on (dom Σ) P →
  (∃ L : aset,
    dom Σ ⊆ L ∧
    ∀ ν,
      ν ∉ L →
      ∀ Hfresh Hresult,
        let_result_world_on e ν m Hfresh Hresult ⊨ P ν) →
  m ⊨ FExprContIn Σ e P.
Proof.
  intros Hty Hdom Hclosed Htotal HPfv HPrename Hcont.
  pose proof (basic_typing_contains_fv_tm _ _ _ Hty) as Hfv.
  destruct Hcont as [L [HL Huse]].
  unfold FExprContIn, fresh_forall, res_models, res_models_with_store.
  simpl.
  split.
  - unfold formula_scoped_in_world.
    simpl.
    rewrite FExprResultOn_fv.
    pose proof (fresh_for_not_in (dom Σ)) as Ha.
    pose proof (HPfv (fresh_for (dom Σ))) as HP.
    rewrite Hdom.
    set_solver.
  - exists (L ∪ dom Σ). split; [rewrite Hdom; set_solver |].
    intros ν Hν m' Hdom' Hrestr.
    assert (HνΣ : ν ∉ dom Σ) by set_solver.
    assert (Hfreshν : ν ∉ world_dom (m : World)) by (rewrite Hdom; exact HνΣ).
    assert (Hresultν : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e)) e →* tret vx).
    { eapply expr_total_on_to_fv_result; eauto. }
    assert (Hbody :
      let_result_world_on e ν m Hfreshν Hresultν ⊨ P ν).
    { eapply Huse; eauto. set_solver. }
    assert (Hscope_impl :
      formula_scoped_in_world ∅ m'
        (formula_rename_atom (fresh_for (dom Σ)) ν
          (FImpl (FExprResultOn (dom Σ) e (fresh_for (dom Σ)))
                 (P (fresh_for (dom Σ)))))).
    {
      replace (formula_rename_atom (fresh_for (dom Σ)) ν
        (FImpl (FExprResultOn (dom Σ) e (fresh_for (dom Σ)))
               (P (fresh_for (dom Σ)))))
        with (FImpl (FExprResultOn (dom Σ) e ν)
              (formula_rename_atom (fresh_for (dom Σ)) ν
                (P (fresh_for (dom Σ))))).
      2:{
        simpl. cbn [dom].
        rewrite FExprResultOn_rename_result_fresh; [reflexivity | |].
        - apply fresh_for_not_in.
        - exact HνΣ.
      }
      unfold formula_scoped_in_world. simpl.
      rewrite FExprResultOn_fv.
      pose proof (fresh_for_not_in (dom Σ)) as Ha.
      pose proof (HPfv (fresh_for (dom Σ))) as HP.
      pose proof (formula_rename_atom_fv_subset_pair
        (dom Σ) (fresh_for (dom Σ)) ν (P (fresh_for (dom Σ)))
        Ha HνΣ HP) as HPren.
      rewrite Hdom', Hdom.
      set_solver.
    }
    assert (Himpl :
      m' ⊨ formula_rename_atom (fresh_for (dom Σ)) ν
        (FImpl (FExprResultOn (dom Σ) e (fresh_for (dom Σ)))
               (P (fresh_for (dom Σ))))).
    {
      eapply res_models_with_store_impl_intro.
      - exact Hscope_impl.
      - intros m'' Hle Hant.
        assert (Hantν : m'' ⊨ FExprResultOn (dom Σ) e ν).
        {
          cbn [dom] in Hant |- *.
          rewrite (FExprResultOn_rename_result_fresh
            (dom Σ) e (fresh_for (dom Σ)) ν) in Hant.
          + exact Hant.
          + apply fresh_for_not_in.
          + exact HνΣ.
        }
        set (S := dom Σ ∪ {[ν]}).
        assert (HS_eq : S = world_dom (m' : World)).
        { unfold S. rewrite Hdom', Hdom. set_solver. }
        assert (Hmin_eq : res_restrict m'' S = m').
        {
          unfold S.
          rewrite <- Hdom, <- Hdom'.
          apply res_restrict_eq_of_le. exact Hle.
        }
        assert (Hant_min : res_restrict m'' S ⊨ FExprResultOn (dom Σ) e ν).
        {
          pose proof (res_models_minimal_on S m'' (FExprResultOn (dom Σ) e ν)
            ltac:(rewrite FExprResultOn_fv; unfold S; set_solver))
            as Hminimal.
          exact (proj1 Hminimal Hantν).
        }
        assert (Hdom_min :
          world_dom (res_restrict m'' S : World) = dom Σ ∪ {[ν]}).
        {
          rewrite Hmin_eq, Hdom'. rewrite Hdom. reflexivity.
        }
        assert (Hrestr_min :
          res_restrict (res_restrict m'' S) (dom Σ) = m).
        {
          rewrite Hmin_eq. rewrite <- Hdom. exact Hrestr.
        }
        pose proof (FExprResultOn_dom_exact_domain_eq_let_result_world_on
          Σ T e ν m (res_restrict m'' S) Hfreshν Hresultν
          Hty Hdom Hclosed Hdom_min Hrestr_min Hant_min) as Hexact.
        assert (Hbody_m'' : m'' ⊨ P ν).
        {
          eapply (res_models_kripke
            (let_result_world_on e ν m Hfreshν Hresultν) m'' (P ν)).
          - rewrite <- Hexact. apply res_restrict_le.
          - exact Hbody.
        }
        apply (proj2 (HPrename (fresh_for (dom Σ)) ν m''
          ltac:(apply fresh_for_not_in) HνΣ)).
        exact Hbody_m''.
    }
    unfold res_models, res_models_with_store in Himpl.
    rewrite formula_rename_preserves_measure in Himpl.
    exact Himpl.
Qed.

Lemma FExprContIn_iff_let_result_world_on_exact_domain
    (Σ : gmap atom ty) (T : ty) e
    (P : atom → FormulaQ) (m : WfWorld) :
  Σ ⊢ₑ e ⋮ T →
  world_dom (m : World) = dom Σ →
  world_store_closed_on (dom Σ) m →
  expr_total_on (dom Σ) e m →
  (∀ ν, formula_fv (P ν) ⊆ dom Σ ∪ {[ν]}) →
  formula_family_rename_stable_on (dom Σ) P →
  m ⊨ FExprContIn Σ e P ↔
  ∃ L : aset,
    dom Σ ⊆ L ∧
    ∀ ν,
      ν ∉ L →
      ∀ Hfresh Hresult,
        let_result_world_on e ν m Hfresh Hresult ⊨ P ν.
Proof.
  intros Hty Hdom Hclosed Htotal HPfv HPrename.
  split.
  - eapply (FExprContIn_to_let_result_world_on_exact_domain Σ T e P m); eauto.
  - eapply (let_result_world_on_to_FExprContIn_exact_domain Σ T e P m); eauto.
Qed.

Lemma expr_total_on_tlete_elim_body_strong
    X e1 e2 x (m : WfWorld) Hfresh Hresult :
  X ⊆ world_dom (m : World) →
  x ∉ X →
  x ∉ fv_tm e2 →
  world_store_closed_on X m →
  lc_tm (tlete e1 e2) →
  expr_total_on X (tlete e1 e2) m →
  expr_total_on (X ∪ {[x]}) (e2 ^^ x)
    (let_result_world_on e1 x m Hfresh Hresult).
Proof.
  intros HXdom HxX Hxe2 Hclosed Hlclet [Hfv Hsn].
  apply lc_lete_iff_body in Hlclet as [Hlc1 Hbody2].
  split.
  - simpl in Hfv.
    pose proof (open_fv_tm e2 (vfvar x) 0) as Hopen_fv.
    simpl in Hopen_fv. set_solver.
  - intros σx Hσx.
    destruct (let_result_world_on_elim e1 x m Hfresh Hresult σx Hσx)
      as [σ [vx [Hσ [Hsteps_fv ->]]]].
    assert (HclosedX : store_closed (store_restrict σ X)).
    { exact (Hclosed σ Hσ). }
    assert (Hfv1 : fv_tm e1 ⊆ X) by (simpl in Hfv; set_solver).
    assert (HstepsX : subst_map (store_restrict σ X) e1 →* tret vx).
    {
      rewrite <- (subst_map_restrict_to_fv_from_superset e1 X σ Hfv1
        (proj1 HclosedX)).
      exact Hsteps_fv.
    }
    assert (Hvx_closed : stale vx = ∅ ∧ is_lc vx).
    {
      eapply steps_closed_result; [| exact HstepsX].
      apply msubst_closed_tm.
      - exact HclosedX.
      - exact Hlc1.
      - change (fv_tm e1 ⊆ dom (store_restrict σ X)).
        rewrite store_restrict_dom.
        pose proof (wfworld_store_dom m σ Hσ) as Hdomσ.
        set_solver.
    }
    assert (Hbody_msubst : body_tm (subst_map (store_restrict σ X) e2)).
    { apply body_tm_msubst; [exact (proj1 HclosedX) | exact (proj2 HclosedX) | exact Hbody2]. }
    assert (Hsnlet :
      strongly_normalizing
        (tlete (subst_map (store_restrict σ X) e1)
               (subst_map (store_restrict σ X) e2))).
    {
      specialize (Hsn σ Hσ).
      change (strongly_normalizing (m{store_restrict σ X} (tlete e1 e2))) in Hsn.
      rewrite msubst_lete in Hsn. exact Hsn.
    }
    pose proof (strongly_normalizing_tlete_elim_body
      (subst_map (store_restrict σ X) e1)
      (subst_map (store_restrict σ X) e2)
      vx Hbody_msubst HstepsX Hsnlet) as Hbody_sn.
    rewrite store_restrict_insert_fresh_union.
    + rewrite (msubst_open_body_result X σ e2 x vx)
        by (try exact HxX; try exact Hxe2; try exact (proj1 HclosedX);
            try exact (proj1 Hvx_closed); try exact (proj2 Hvx_closed);
            try exact (proj2 HclosedX)).
      exact Hbody_sn.
    + eapply store_lookup_none_of_dom.
      * exact (wfworld_store_dom m σ Hσ).
      * exact Hfresh.
    + exact HxX.
Qed.

Lemma basic_typing_tlete_body_for_fresh Γ e1 e2 T1 T2 x :
  Γ ⊢ₑ e1 ⋮ T1 →
  Γ ⊢ₑ tlete e1 e2 ⋮ T2 →
  x ∉ dom Γ ∪ fv_tm e2 →
  <[x := T1]> Γ ⊢ₑ e2 ^^ x ⋮ T2.
Proof.
  intros He1 Hlet Hxfresh.
  inversion Hlet; subst.
  assert (T0 = T1) as ->.
  { eapply basic_typing_unique_tm; eauto. }
  pose (y := fresh_for (L ∪ dom Γ ∪ fv_tm e2 ∪ {[x]})).
  assert (Hy : y ∉ L ∪ dom Γ ∪ fv_tm e2 ∪ {[x]})
    by (subst y; apply fresh_for_not_in).
  match goal with
  | Hopen : ∀ z : atom, z ∉ L → <[z:=T1]> Γ ⊢ₑ e2 ^^ z ⋮ T2 |- _ =>
      pose proof (Hopen y ltac:(set_solver)) as Hybody
  end.
  eapply basic_typing_open_tm with (x := y) (U := T1).
  - set_solver.
  - constructor. apply lookup_insert_eq.
  - replace (<[y:=T1]> (<[x:=T1]> Γ))
      with (<[x:=T1]> (<[y:=T1]> Γ))
      by (rewrite insert_insert_ne by set_solver; reflexivity).
    eapply basic_typing_weaken_insert_tm.
    + rewrite dom_insert_L. set_solver.
    + exact Hybody.
Qed.

(** Continuation-style expression-result principle for [tlet].

    This is the stabilized version of the earlier fibered statement.  The
    continuation [Q] is kept abstract: the [tlet] reduction should not know
    whether the result type later wraps [Q ν] in fibers, modalities, or other
    type constructors.

    The exact-domain premise [world_dom m = dom Σ] is essential.  [FExprContIn]
    fibers over [dom Σ], while [let_result_world_on] extends the whole input
    world; these line up definitionally only when the input world is already
    minimal for [Σ].  The strong whole-let totality premise is enough to recover
    the body totality needed by the exact-domain bridge; do not reintroduce
    separate may-total assumptions here.  Do not split this lemma by the shape of
    the result type; it is meant to be a type-constructor-independent bridge used
    by the [tlet] case. *)
Lemma FExprCont_tlet_reduction
    (Σ : gmap atom ty) (T1 T2 : ty)
    (m : WfWorld) e1 e2 (x : atom) (Q : atom → FormulaQ)
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx) :
  Σ ⊢ₑ e1 ⋮ T1 →
  Σ ⊢ₑ tlete e1 e2 ⋮ T2 →
  x ∉ fv_tm e2 →
  world_dom (m : World) = dom Σ →
  world_store_closed_on (dom Σ) m →
  expr_total_on (dom Σ) (tlete e1 e2) m →
  (∀ ν, formula_fv (Q ν) ⊆ dom Σ ∪ {[ν]}) →
  formula_family_rename_stable_on (dom Σ) Q →
  let_result_world_on e1 x m Hfresh Hresult
    ⊨ FExprContIn (<[x := T1]> Σ) (e2 ^^ x) Q ↔
  m ⊨ FExprContIn Σ (tlete e1 e2) Q.
Proof.
  intros He1 Hlet Hxe2 Hdom Hclosed Htotal_let HQfv HQrename.
  set (m1 := let_result_world_on e1 x m Hfresh Hresult).
  assert (HxΣ : x ∉ dom Σ).
  { rewrite <- Hdom. exact Hfresh. }
  assert (He2 : <[x := T1]> Σ ⊢ₑ e2 ^^ x ⋮ T2).
  { eapply basic_typing_tlete_body_for_fresh; eauto; set_solver. }
  assert (Hdom_m1 : world_dom (m1 : World) = dom (<[x := T1]> Σ)).
  {
    subst m1. rewrite let_result_world_on_dom, Hdom, dom_insert_L.
    set_solver.
  }
  assert (Hfv1 : fv_tm e1 ⊆ dom Σ).
  { apply basic_typing_contains_fv_tm in He1. exact He1. }
  assert (Hlc1 : lc_tm e1).
  { apply typing_tm_lc with (Γ := Σ) (T := T1). exact He1. }
  assert (Hclosed_m1 :
    world_store_closed_on (dom (<[x := T1]> Σ)) m1).
  {
    subst m1. rewrite dom_insert_L.
    replace ({[x]} ∪ dom Σ) with (dom Σ ∪ {[x]}) by set_solver.
    eapply let_result_world_on_store_closed_on_insert.
    - exact HxΣ.
    - exact Hclosed.
    - intros σ vx Hσ Hsteps.
      assert (Hclosed_fv : world_store_closed_on (fv_tm e1) m).
      { eapply world_store_closed_on_mono; [exact Hfv1 | exact Hclosed]. }
      eapply (steps_closed_result_of_restrict_world
        (fv_tm e1) e1 m (store_restrict σ (fv_tm e1)) vx).
      + rewrite Hdom. exact Hfv1.
      + set_solver.
      + exact Hlc1.
      + exact Hclosed_fv.
      + exists σ. split; [exact Hσ | reflexivity].
      + replace (store_restrict (store_restrict σ (fv_tm e1)) (fv_tm e1))
          with (store_restrict σ (fv_tm e1)).
        * exact Hsteps.
        * store_norm. reflexivity.
  }
  assert (Htotal2 :
    expr_total_on (dom (<[x := T1]> Σ)) (e2 ^^ x) m1).
  {
    subst m1. rewrite dom_insert_L.
    replace ({[x]} ∪ dom Σ) with (dom Σ ∪ {[x]}) by set_solver.
    eapply (expr_total_on_tlete_elim_body_strong
      (dom Σ) e1 e2 x m Hfresh Hresult).
    - rewrite Hdom. set_solver.
    - exact HxΣ.
    - exact Hxe2.
    - exact Hclosed.
    - eapply typing_tm_lc; eauto.
    - exact Htotal_let.
  }
  assert (HQfv_insert :
    ∀ ν, formula_fv (Q ν) ⊆ dom (<[x := T1]> Σ) ∪ {[ν]}).
  {
    intros ν. specialize (HQfv ν). rewrite dom_insert_L. set_solver.
  }
  assert (HQrename_insert :
    formula_family_rename_stable_on (dom (<[x := T1]> Σ)) Q).
  {
    unfold formula_family_rename_stable_on in *.
    intros a b n Ha Hb.
    apply HQrename; rewrite dom_insert_L in *; set_solver.
  }
  assert (Hdecompose_side :
    ∀ ν Hfreshν_body Hresultν_body Hfreshν_tlet Hresultν_tlet,
      ν ∉ dom Σ ∪ {[x]} ∪ fv_tm e2 →
      res_restrict
        (let_result_world_on (e2 ^^ x) ν m1 Hfreshν_body Hresultν_body)
        (world_dom (m : World) ∪ {[ν]}) =
      let_result_world_on (tlete e1 e2) ν m Hfreshν_tlet Hresultν_tlet).
  {
    intros ν Hfreshν_body Hresultν_body Hfreshν_tlet Hresultν_tlet Hνfresh.
    unfold m1.
    rewrite (let_result_world_on_tlete_decompose
      (dom Σ) e1 e2 x ν m
      Hfresh Hresult Hfreshν_body Hresultν_body
      Hfreshν_tlet Hresultν_tlet).
    - reflexivity.
    - apply basic_typing_contains_fv_tm in Hlet. exact Hlet.
    - apply basic_typing_contains_fv_tm in Hlet. simpl in Hlet. set_solver.
    - exact Hfreshν_tlet.
    - rewrite Hdom. set_solver.
    - intros σ Hσ. exact (proj1 (Hclosed σ Hσ)).
    - intros σ Hσ. exact (proj2 (Hclosed σ Hσ)).
    - intros σ vx Hσ Hsteps.
      eapply steps_closed_result.
      + eapply (msubst_closed_tm_of_restrict_world (dom Σ) e1 m σ).
        * rewrite Hdom. set_solver.
        * exact Hfv1.
        * exact Hlc1.
        * exact Hclosed.
        * exists σ. split; [exact Hσ |].
          rewrite (store_restrict_idemp σ (dom Σ)).
          -- reflexivity.
          -- pose proof (wfworld_store_dom m σ Hσ) as Hdomσ.
             set_solver.
      + exact Hsteps.
    - intros σ Hσ.
      pose proof (typing_tm_lc _ _ _ Hlet) as Hlclet.
      apply lc_lete_iff_body in Hlclet as [_ Hbodye2].
      eapply body_tm_msubst.
      + exact (proj1 (Hclosed σ Hσ)).
      + exact (proj2 (Hclosed σ Hσ)).
      + exact Hbodye2.
  }
  split.
  - intros Hcont.
    pose proof (proj1
      (FExprContIn_iff_let_result_world_on_exact_domain
        (<[x := T1]> Σ) T2 (e2 ^^ x) Q m1
        He2 Hdom_m1 Hclosed_m1 Htotal2 HQfv_insert HQrename_insert)
      Hcont) as [L [HLdom Hbody]].
    apply (proj2
      (FExprContIn_iff_let_result_world_on_exact_domain
        Σ T2 (tlete e1 e2) Q m
        Hlet Hdom Hclosed Htotal_let HQfv HQrename)).
    exists (L ∪ dom Σ ∪ {[x]} ∪ fv_tm e2).
    split; [set_solver |].
    intros ν Hν Hfreshν_tlet Hresultν_tlet.
    assert (Hfreshν_body : ν ∉ world_dom (m1 : World)).
    {
      subst m1. rewrite let_result_world_on_dom, Hdom. set_solver.
    }
    assert (Hresultν_body :
      ∀ σ, (m1 : World) σ →
        ∃ vx, subst_map (store_restrict σ (fv_tm (e2 ^^ x)))
          (e2 ^^ x) →* tret vx).
    {
      eapply expr_total_on_to_fv_result; eauto.
    }
    pose proof (Hbody ν ltac:(set_solver) Hfreshν_body Hresultν_body)
      as Hnested.
    pose proof (proj1 (res_models_minimal_on
      (dom Σ ∪ {[ν]})
      (let_result_world_on (e2 ^^ x) ν m1 Hfreshν_body Hresultν_body)
      (Q ν) (HQfv ν)) Hnested) as Hnested_min.
    replace (dom Σ ∪ {[ν]}) with (world_dom (m : World) ∪ {[ν]})
      in Hnested_min by (rewrite Hdom; reflexivity).
    rewrite (Hdecompose_side ν Hfreshν_body Hresultν_body
      Hfreshν_tlet Hresultν_tlet ltac:(set_solver)) in Hnested_min.
    exact Hnested_min.
  - intros Hcont.
    pose proof (proj1
      (FExprContIn_iff_let_result_world_on_exact_domain
        Σ T2 (tlete e1 e2) Q m
        Hlet Hdom Hclosed Htotal_let HQfv HQrename)
      Hcont) as [L [HLdom Hwhole]].
    apply (proj2
      (FExprContIn_iff_let_result_world_on_exact_domain
        (<[x := T1]> Σ) T2 (e2 ^^ x) Q m1
        He2 Hdom_m1 Hclosed_m1 Htotal2 HQfv_insert HQrename_insert)).
    exists (L ∪ dom Σ ∪ {[x]} ∪ fv_tm e2).
    split; [rewrite dom_insert_L; set_solver |].
    intros ν Hν Hfreshν_body Hresultν_body.
    assert (Hfreshν_tlet : ν ∉ world_dom (m : World)).
    { rewrite Hdom. set_solver. }
    assert (Hresultν_tlet :
      ∀ σ, (m : World) σ →
        ∃ vx, subst_map (store_restrict σ (fv_tm (tlete e1 e2)))
          (tlete e1 e2) →* tret vx).
    {
      eapply expr_total_on_to_fv_result; eauto.
    }
    pose proof (Hwhole ν ltac:(set_solver) Hfreshν_tlet Hresultν_tlet)
      as Hwholeν.
    assert (Hrestrict :
      res_restrict
        (let_result_world_on (e2 ^^ x) ν m1 Hfreshν_body Hresultν_body)
        (dom Σ ∪ {[ν]}) ⊨ Q ν).
    {
      replace (dom Σ ∪ {[ν]}) with (world_dom (m : World) ∪ {[ν]})
        by (rewrite Hdom; reflexivity).
      rewrite (Hdecompose_side ν Hfreshν_body Hresultν_body
        Hfreshν_tlet Hresultν_tlet ltac:(set_solver)).
      exact Hwholeν.
    }
    exact (proj2 (res_models_minimal_on
      (dom Σ ∪ {[ν]})
      (let_result_world_on (e2 ^^ x) ν m1 Hfreshν_body Hresultν_body)
      (Q ν) (HQfv ν)) Hrestrict).
Qed.

Lemma denot_ty_fuel_tlet_reduction_formula_on_arrow_case
    gas (Δ : gmap atom ty) (T1 : ty) (e1 e2 : tm)
    (m : WfWorld) (x : atom)
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx)
    τx τ :
  Δ ⊢ₑ e1 ⋮ T1 →
  Δ ⊢ₑ tlete e1 e2 ⋮ erase_ty (CTArrow τx τ) →
  world_dom (m : World) = dom Δ →
  world_store_closed_on (dom Δ) m →
  expr_total_on (dom Δ) (tlete e1 e2) m →
  x ∉ dom Δ ∪ fv_tm e2 →
  cty_measure (CTArrow τx τ) <= S gas →
  basic_choice_ty (dom Δ) (CTArrow τx τ) →
  let_result_world_on e1 x m Hfresh Hresult ⊨
    fresh_forall (dom (<[x:=T1]> Δ)) (fun y =>
      FImpl
        (denot_ty_fuel gas (<[y:=erase_ty τx]> (<[x:=T1]> Δ)) τx
          (tret (vfvar y)))
        (denot_ty_fuel gas (<[y:=erase_ty τx]> (<[x:=T1]> Δ))
          ({0 ~> y} τ) (tapp_tm (e2 ^^ x) (vfvar y)))) <->
  m ⊨
    fresh_forall (dom Δ) (fun y =>
      FImpl
        (denot_ty_fuel gas (<[y:=erase_ty τx]> Δ) τx
          (tret (vfvar y)))
        (denot_ty_fuel gas (<[y:=erase_ty τx]> Δ)
          ({0 ~> y} τ) (tapp_tm (tlete e1 e2) (vfvar y)))).
Proof.
Admitted.

Lemma denot_ty_fuel_tlet_reduction_formula_on_wand_case
    gas (Δ : gmap atom ty) (T1 : ty) (e1 e2 : tm)
    (m : WfWorld) (x : atom)
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx)
    τx τ :
  Δ ⊢ₑ e1 ⋮ T1 →
  Δ ⊢ₑ tlete e1 e2 ⋮ erase_ty (CTWand τx τ) →
  world_dom (m : World) = dom Δ →
  world_store_closed_on (dom Δ) m →
  expr_total_on (dom Δ) (tlete e1 e2) m →
  x ∉ dom Δ ∪ fv_tm e2 →
  cty_measure (CTWand τx τ) <= S gas →
  basic_choice_ty (dom Δ) (CTWand τx τ) →
  let_result_world_on e1 x m Hfresh Hresult ⊨
    fresh_forall (dom (<[x:=T1]> Δ)) (fun y =>
      FWand
        (denot_ty_fuel gas (<[y:=erase_ty τx]> (<[x:=T1]> Δ)) τx
          (tret (vfvar y)))
        (denot_ty_fuel gas (<[y:=erase_ty τx]> (<[x:=T1]> Δ))
          ({0 ~> y} τ) (tapp_tm (e2 ^^ x) (vfvar y)))) <->
  m ⊨
    fresh_forall (dom Δ) (fun y =>
      FWand
        (denot_ty_fuel gas (<[y:=erase_ty τx]> Δ) τx
          (tret (vfvar y)))
        (denot_ty_fuel gas (<[y:=erase_ty τx]> Δ)
          ({0 ~> y} τ) (tapp_tm (tlete e1 e2) (vfvar y)))).
Proof.
Admitted.

Lemma denot_ty_fuel_tlet_reduction_formula_on gas
    (Δ : gmap atom ty) (T1 : ty) (e1 e2 : tm)
    (m : WfWorld) (x : atom)
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx) :
  Δ ⊢ₑ e1 ⋮ T1 →
  world_dom (m : World) = dom Δ →
  world_store_closed_on (dom Δ) m →
  expr_total_on (dom Δ) (tlete e1 e2) m →
  x ∉ dom Δ ∪ fv_tm e2 →
  ∀ τ2,
    cty_measure τ2 <= gas →
    basic_choice_ty (dom Δ) τ2 →
    Δ ⊢ₑ tlete e1 e2 ⋮ erase_ty τ2 →
    let_result_world_on e1 x m Hfresh Hresult
      ⊨ denot_ty_fuel gas (<[x:=T1]> Δ) τ2 (e2 ^^ x)
    <->
    m ⊨ denot_ty_fuel gas Δ τ2 (tlete e1 e2).
Proof.
  revert Δ T1 e1 e2 m x Hfresh Hresult.
  induction gas as [|gas IH]; intros Δ T1 e1 e2 m x Hfresh Hresult
    He1 Hdom Hclosed Htotal Hx_base τ2 Hgas Hbasicτ Hlet.
  - pose proof (cty_measure_gt_0 τ2). lia.
  - assert (HxΔ : x ∉ dom Δ) by set_solver.
    destruct τ2 as [b φ|b φ|τa τb|τa τb|τa τb|τx τ|τx τ];
      cbn [cty_measure denot_ty_fuel denot_ty_fuel_result denot_ty_formula
        mk_denot_ty_result fv_cty erase_ty] in Hgas, Hbasicτ, Hlet |- *.
    + inversion Hbasicτ as [D b' φ' Hqbody| | | | | |]; subst.
      assert (Hφ : qual_dom φ ⊆ dom Δ).
      { eapply basic_qualifier_body_fv_subset. exact Hqbody. }
      rewrite (FExprContIn_post_eq_at_fresh
        (<[x:=T1]> Δ) (e2 ^^ x)
        (fun ν =>
          let φν := qual_open_atom 0 ν φ in
          FAnd
            (basic_world_formula (<[ν:=TBase b]> (<[x:=T1]> Δ))
              ({[ν]} ∪ qual_dom φν))
            (fib_vars (qual_dom φν)
              (FOver (FAtom (lift_type_qualifier_to_logic φν)))))
        (fun ν =>
          let φν := qual_open_atom 0 ν φ in
          FAnd
            (basic_world_formula (<[ν:=TBase b]> Δ)
              ({[ν]} ∪ qual_dom φν))
            (fib_vars (qual_dom φν)
              (FOver (FAtom (lift_type_qualifier_to_logic φν)))))).
      2:{
        eapply (denot_refinement_over_cont_insert_fresh_eq
          (dom Δ : aset) Δ x T1 b φ); [set_solver | reflexivity].
      }
      eapply (FExprCont_tlet_reduction
        Δ T1 (TBase b) m e1 e2 x).
      * exact He1.
      * exact Hlet.
      * set_solver.
      * exact Hdom.
      * exact Hclosed.
      * exact Htotal.
      * eapply denot_refinement_over_cont_fv_subset. exact Hφ.
      * eapply denot_refinement_over_cont_rename_stable. exact Hφ.
    + inversion Hbasicτ as [|D b' φ' Hqbody| | | | |]; subst.
      assert (Hφ : qual_dom φ ⊆ dom Δ).
      { eapply basic_qualifier_body_fv_subset. exact Hqbody. }
      rewrite (FExprContIn_post_eq_at_fresh
        (<[x:=T1]> Δ) (e2 ^^ x)
        (fun ν =>
          let φν := qual_open_atom 0 ν φ in
          FAnd
            (basic_world_formula (<[ν:=TBase b]> (<[x:=T1]> Δ))
              ({[ν]} ∪ qual_dom φν))
            (fib_vars (qual_dom φν)
              (FUnder (FAtom (lift_type_qualifier_to_logic φν)))))
        (fun ν =>
          let φν := qual_open_atom 0 ν φ in
          FAnd
            (basic_world_formula (<[ν:=TBase b]> Δ)
              ({[ν]} ∪ qual_dom φν))
            (fib_vars (qual_dom φν)
              (FUnder (FAtom (lift_type_qualifier_to_logic φν)))))).
      2:{
        eapply (denot_refinement_under_cont_insert_fresh_eq
          (dom Δ : aset) Δ x T1 b φ); [set_solver | reflexivity].
      }
      eapply (FExprCont_tlet_reduction
        Δ T1 (TBase b) m e1 e2 x).
      * exact He1.
      * exact Hlet.
      * set_solver.
      * exact Hdom.
      * exact Hclosed.
      * exact Htotal.
      * eapply denot_refinement_under_cont_fv_subset. exact Hφ.
      * eapply denot_refinement_under_cont_rename_stable. exact Hφ.
    + inversion Hbasicτ as [| |D τ1' τ2' HbasicA HbasicB Herase| | | |]; subst.
      assert (HIHa :
        let_result_world_on e1 x m Hfresh Hresult ⊨
          denot_ty_fuel gas (<[x:=T1]> Δ) τa
            (e2 ^^ x) <->
        m ⊨ denot_ty_fuel gas Δ τa (tlete e1 e2)).
      {
        eapply (IH Δ T1 e1 e2 m x Hfresh Hresult).
        - exact He1.
        - exact Hdom.
        - exact Hclosed.
        - exact Htotal.
        - exact Hx_base.
        - lia.
        - exact HbasicA.
        - exact Hlet.
      }
      assert (HIHb :
        let_result_world_on e1 x m Hfresh Hresult ⊨
          denot_ty_fuel gas (<[x:=T1]> Δ) τb
            (e2 ^^ x) <->
        m ⊨ denot_ty_fuel gas Δ τb (tlete e1 e2)).
      {
        eapply (IH Δ T1 e1 e2 m x Hfresh Hresult).
        - exact He1.
        - exact Hdom.
        - exact Hclosed.
        - exact Htotal.
        - exact Hx_base.
        - lia.
        - exact HbasicB.
        - replace (erase_ty τb) with (erase_ty τa) by congruence.
          exact Hlet.
      }
      split; intros Hmodel.
      * apply res_models_and_intro_from_models.
        -- apply (proj1 HIHa). eapply res_models_and_elim_l. exact Hmodel.
        -- apply (proj1 HIHb). eapply res_models_and_elim_r. exact Hmodel.
      * apply res_models_and_intro_from_models.
        -- apply (proj2 HIHa). eapply res_models_and_elim_l. exact Hmodel.
        -- apply (proj2 HIHb). eapply res_models_and_elim_r. exact Hmodel.
    + inversion Hbasicτ as [| | |D τ1' τ2' HbasicA HbasicB Herase| | |]; subst.
      assert (HIHa :
        let_result_world_on e1 x m Hfresh Hresult ⊨
          denot_ty_fuel gas (<[x:=T1]> Δ) τa
            (e2 ^^ x) <->
        m ⊨ denot_ty_fuel gas Δ τa (tlete e1 e2)).
      {
        eapply (IH Δ T1 e1 e2 m x Hfresh Hresult).
        - exact He1.
        - exact Hdom.
        - exact Hclosed.
        - exact Htotal.
        - exact Hx_base.
        - lia.
        - exact HbasicA.
        - exact Hlet.
      }
      assert (HIHb :
        let_result_world_on e1 x m Hfresh Hresult ⊨
          denot_ty_fuel gas (<[x:=T1]> Δ) τb
            (e2 ^^ x) <->
        m ⊨ denot_ty_fuel gas Δ τb (tlete e1 e2)).
      {
        eapply (IH Δ T1 e1 e2 m x Hfresh Hresult).
        - exact He1.
        - exact Hdom.
        - exact Hclosed.
        - exact Htotal.
        - exact Hx_base.
        - lia.
        - exact HbasicB.
        - replace (erase_ty τb) with (erase_ty τa) by congruence.
          exact Hlet.
      }
      split; intros Hmodel.
      * unfold res_models, res_models_with_store in Hmodel.
        simpl in Hmodel. destruct Hmodel as [_ [Ha | Hb]].
        -- eapply res_models_or_intro_l_from_model.
           ++ apply (proj1 HIHa). unfold res_models, res_models_with_store.
              lazymatch type of Ha with
              | res_models_with_store_fuel ?g ?ρ ?n ?φ =>
                  eapply (res_models_with_store_fuel_irrel g (formula_measure φ) ρ n φ);
                  [simpl; lia | lia | exact Ha]
              end.
           ++ rewrite Hdom.
              eapply denot_ty_fuel_formula_fv_subset_env; [lia |].
              eapply basic_choice_ty_fv_subset. exact HbasicB.
        -- eapply res_models_or_intro_r_from_model.
           ++ rewrite Hdom.
              eapply denot_ty_fuel_formula_fv_subset_env; [lia |].
              eapply basic_choice_ty_fv_subset. exact HbasicA.
           ++ apply (proj1 HIHb). unfold res_models, res_models_with_store.
              lazymatch type of Hb with
              | res_models_with_store_fuel ?g ?ρ ?n ?φ =>
                  eapply (res_models_with_store_fuel_irrel g (formula_measure φ) ρ n φ);
                  [simpl; lia | lia | exact Hb]
              end.
      * unfold res_models, res_models_with_store in Hmodel.
        simpl in Hmodel. destruct Hmodel as [_ [Ha | Hb]].
        -- eapply res_models_or_intro_l_from_model.
           ++ apply (proj2 HIHa). unfold res_models, res_models_with_store.
              lazymatch type of Ha with
              | res_models_with_store_fuel ?g ?ρ ?n ?φ =>
                  eapply (res_models_with_store_fuel_irrel g (formula_measure φ) ρ n φ);
                  [simpl; lia | lia | exact Ha]
              end.
           ++ rewrite let_result_world_on_dom, Hdom.
              pose proof (denot_ty_fuel_formula_fv_subset_env
                gas (<[x:=T1]> Δ) τb (e2 ^^ x) ltac:(lia)
                ltac:(rewrite dom_insert_L;
                  pose proof (basic_choice_ty_fv_subset (dom Δ) τb HbasicB);
                  set_solver)) as Hfv.
              intros z Hz. apply Hfv in Hz. rewrite dom_insert_L in Hz. set_solver.
        -- eapply res_models_or_intro_r_from_model.
           ++ rewrite let_result_world_on_dom, Hdom.
              pose proof (denot_ty_fuel_formula_fv_subset_env
                gas (<[x:=T1]> Δ) τa (e2 ^^ x) ltac:(lia)
                ltac:(rewrite dom_insert_L;
                  pose proof (basic_choice_ty_fv_subset (dom Δ) τa HbasicA);
                  set_solver)) as Hfv.
              intros z Hz. apply Hfv in Hz. rewrite dom_insert_L in Hz. set_solver.
           ++ apply (proj2 HIHb). unfold res_models, res_models_with_store.
              lazymatch type of Hb with
              | res_models_with_store_fuel ?g ?ρ ?n ?φ =>
                  eapply (res_models_with_store_fuel_irrel g (formula_measure φ) ρ n φ);
                  [simpl; lia | lia | exact Hb]
              end.
    + (* CTSum: the recursive calls happen under the two summand subresources.
         Their domains should be recovered from formula scoping plus
         [denot_ty_fuel_env_fv_subset]. *)
      admit.
    + eapply denot_ty_fuel_tlet_reduction_formula_on_arrow_case; eauto.
    + eapply denot_ty_fuel_tlet_reduction_formula_on_wand_case; eauto.
Admitted.

Lemma denot_ty_fuel_tlet_reduction_formula gas (τ2 : choice_ty): forall
    (Σ : gmap atom ty) (Γ : ctx) (τ1: choice_ty) e1 e2
    (m : WfWorld) x
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx),
  cty_measure τ2 <= gas →
  denot_ty_regular_in_ctx_under Σ Γ τ2 →
  erase_ctx_under Σ Γ ⊢ₑ e1 ⋮ erase_ty τ1 →
  erase_ctx_under Σ Γ ⊢ₑ tlete e1 e2 ⋮ erase_ty τ2 →
  world_dom (m : World) = dom (erase_ctx_under Σ Γ) →
  world_store_closed_on (dom (erase_ctx_under Σ Γ)) m →
  expr_total_on (dom (erase_ctx_under Σ Γ)) (tlete e1 e2) m →
  x ∉ dom (erase_ctx_under Σ Γ) ∪ fv_cty τ2 ∪ fv_tm e2 →
  let_result_world_on e1 x m Hfresh Hresult
    ⊨ denot_ty_fuel gas (erase_ctx_under Σ (CtxComma Γ (CtxBind x τ1)))
        τ2 (e2 ^^ x)
  <->
  m ⊨ denot_ty_fuel gas (erase_ctx_under Σ Γ) τ2 (tlete e1 e2).
Proof.
  intros Σ Γ τ1 e1 e2 m x Hfresh Hresult
    Hgas [HbasicΓ Hbasicτ] He1 Hlet Hdom Hclosed Htotal Hx.
  assert (HxΔ : x ∉ dom (erase_ctx_under Σ Γ)) by set_solver.
  rewrite (erase_ctx_under_comma_bind_env_fresh Σ Γ x τ1)
    by exact HxΔ.
  eapply (denot_ty_fuel_tlet_reduction_formula_on
    gas (erase_ctx_under Σ Γ) (erase_ty τ1) e1 e2 m x
    Hfresh Hresult); eauto.
  set_solver.
Qed.

Lemma denot_ty_tlet_reduction_formula (τ2 : choice_ty): forall
    (Σ : gmap atom ty) (Γ : ctx) (τ1: choice_ty) e1 e2
    (m : WfWorld) x
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx),
  denot_ty_regular_in_ctx_under Σ Γ τ2 →
  erase_ctx_under Σ Γ ⊢ₑ e1 ⋮ erase_ty τ1 →
  erase_ctx_under Σ Γ ⊢ₑ tlete e1 e2 ⋮ erase_ty τ2 →
  world_dom (m : World) = dom (erase_ctx_under Σ Γ) →
  m ⊨ denot_ctx_in_env Σ Γ →
  expr_total_on (dom (erase_ctx_under Σ Γ)) (tlete e1 e2) m →
  x ∉ dom (erase_ctx_under Σ Γ) ∪ fv_cty τ2 ∪ fv_tm e2 →
  let_result_world_on e1 x m Hfresh Hresult
    ⊨ denot_ty_in_ctx_under Σ (CtxComma Γ (CtxBind x τ1)) τ2 (e2 ^^ x)
  <->
  m ⊨ denot_ty_in_ctx_under Σ Γ τ2 (tlete e1 e2).
Proof.
  intros Σ Γ τ1 e1 e2 m x Hfresh Hresult Hregular He1 Hlet Hdom Hctx Htotal Hx.
  unfold denot_ty_in_ctx_under, denot_ty_on.
  eapply denot_ty_fuel_tlet_reduction_formula; eauto.
  eapply denot_ctx_in_env_world_store_closed_on_erased; eauto.
  exact (proj1 Hregular).
Qed.

Lemma denot_ty_tlet_reduction_formula_any_world (τ2 : choice_ty): forall
    (Σ : gmap atom ty) (Γ : ctx) (τ1: choice_ty) e1 e2
    (m : WfWorld) x
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx),
  denot_ty_regular_in_ctx_under Σ Γ τ2 →
  erase_ctx_under Σ Γ ⊢ₑ e1 ⋮ erase_ty τ1 →
  erase_ctx_under Σ Γ ⊢ₑ tlete e1 e2 ⋮ erase_ty τ2 →
  m ⊨ denot_ctx_in_env Σ Γ →
  expr_total_on (dom (erase_ctx_under Σ Γ)) (tlete e1 e2) m →
  x ∉ dom (erase_ctx_under Σ Γ) ∪ fv_cty τ2 ∪ fv_tm e2 →
  let_result_world_on e1 x m Hfresh Hresult
    ⊨ denot_ty_in_ctx_under Σ (CtxComma Γ (CtxBind x τ1)) τ2 (e2 ^^ x)
  <->
  m ⊨ denot_ty_in_ctx_under Σ Γ τ2 (tlete e1 e2).
Proof.
Admitted.

Lemma expr_total_tlet_reduction
    (Σ : gmap atom ty) (Γ : ctx) (τ1 τ2 : choice_ty) e1 e2
    (m : WfWorld) x
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx) :
  erase_ctx_under Σ Γ ⊢ₑ tlete e1 e2 ⋮ erase_ty τ2 →
  m ⊨ denot_ctx_in_env Σ Γ →
  x ∉ dom (erase_ctx_under Σ Γ) ∪ fv_tm e2 →
  expr_total_on (dom (erase_ctx_under Σ (CtxComma Γ (CtxBind x τ1))))
    (e2 ^^ x)
    (let_result_world_on e1 x m Hfresh Hresult)
  <->
  expr_total_on (dom (erase_ctx_under Σ Γ)) (tlete e1 e2) m.
Proof.
Admitted.

Lemma denot_ty_regular_tlet_context_iff
    (Σ : gmap atom ty) (Γ : ctx) (τ1 τ2 : choice_ty) x :
  x ∉ dom (erase_ctx_under Σ Γ) ∪ fv_cty τ2 →
  denot_ty_regular_in_ctx_under Σ Γ τ1 →
  denot_ty_regular_in_ctx_under Σ (CtxComma Γ (CtxBind x τ1)) τ2 ↔
  denot_ty_regular_in_ctx_under Σ Γ τ2.
Proof.
  intros Hfresh [HctxΓ Hτ1]. split.
  - intros [Hctxcomma Hτ2_body].
    split.
    + inversion Hctxcomma; subst; assumption.
    + eapply basic_choice_ty_drop_fresh.
      * intros Hxτ. apply Hfresh. apply elem_of_union_r. exact Hxτ.
      * replace (dom (erase_ctx_under Σ Γ) ∪ {[x]}) with
          (dom (erase_ctx_under Σ (CtxComma Γ (CtxBind x τ1)))).
        -- exact Hτ2_body.
        -- rewrite erase_ctx_under_comma_bind_dom_nf. set_solver.
  - intros [HctxΓ' Hτ2].
    split.
    + eapply Basic_CtxComma.
      * exact HctxΓ'.
      * eapply Basic_CtxBind.
        -- rewrite <- (erase_ctx_under_dom_basic Σ Γ HctxΓ').
           set_solver.
        -- replace (dom Σ ∪ ctx_dom Γ) with
             (dom (erase_ctx_under Σ Γ)).
           ++ exact Hτ1.
           ++ rewrite erase_ctx_under_dom_basic by exact HctxΓ'. set_solver.
      * simpl. pose proof (erase_ctx_under_dom_basic Σ Γ HctxΓ') as HdomΓ.
        set_solver.
    + rewrite erase_ctx_under_comma_bind_dom_nf.
      eapply (basic_choice_ty_mono
        (dom (erase_ctx_under Σ Γ))
        (dom (erase_ctx_under Σ Γ) ∪ {[x]})); [set_solver | exact Hτ2].
Qed.

Lemma denot_ty_total_tlet_reduction
    (Σ : gmap atom ty) (Γ : ctx) (τ1 τ2 : choice_ty) e1 e2
    (m : WfWorld) x
    (Hfresh : x ∉ world_dom (m : World))
    (Hresult : ∀ σ, (m : World) σ →
      ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx) :
  erase_ctx_under Σ Γ ⊢ₑ e1 ⋮ erase_ty τ1 →
  erase_ctx_under Σ Γ ⊢ₑ tlete e1 e2 ⋮ erase_ty τ2 →
  m ⊨ denot_ctx_in_env Σ Γ →
  denot_ty_total_model_in_ctx_under Σ Γ τ1 e1 m →
  x ∉ dom (erase_ctx_under Σ Γ) ∪ fv_cty τ2 ∪ fv_tm e2 →
  denot_ty_total_model_in_ctx_under Σ (CtxComma Γ (CtxBind x τ1)) τ2
    (e2 ^^ x)
    (let_result_world_on e1 x m Hfresh Hresult)
  <->
  denot_ty_total_model_in_ctx_under Σ Γ τ2 (tlete e1 e2) m.
Proof.
  intros He1 Hlet Hctx Hmodel1 Hfreshx.
  pose proof (denot_ty_regular_tlet_context_iff
    Σ Γ τ1 τ2 x ltac:(set_solver)
    (denot_ty_total_model_regular Σ Γ τ1 e1 m Hmodel1))
    as Hregular_iff.
	  split; intros Hmodel.
	  - destruct Hmodel as [[Hregular_body Hformula_body] Htotal_body].
	    pose proof (proj1 (expr_total_tlet_reduction
	      Σ Γ τ1 τ2 e1 e2 m x Hfresh Hresult Hlet Hctx ltac:(set_solver))
	      Htotal_body) as Htotal_target.
	    split.
	    + split.
	      * apply (proj1 Hregular_iff). exact Hregular_body.
		      * apply (proj1 (denot_ty_tlet_reduction_formula_any_world
		          τ2 Σ Γ τ1 e1 e2 m x Hfresh Hresult
		          (proj1 Hregular_iff Hregular_body) He1 Hlet Hctx
		          Htotal_target Hfreshx)).
	        exact Hformula_body.
	    + exact Htotal_target.
	  - destruct Hmodel as [[Hregular_target Hformula_target] Htotal_target].
	    split.
	    + split.
	      * apply (proj2 Hregular_iff). exact Hregular_target.
		      * apply (proj2 (denot_ty_tlet_reduction_formula_any_world
		          τ2 Σ Γ τ1 e1 e2 m x Hfresh Hresult
		          Hregular_target He1 Hlet Hctx Htotal_target Hfreshx)).
	        exact Hformula_target.
    + apply (proj2 (expr_total_tlet_reduction
        Σ Γ τ1 τ2 e1 e2 m x Hfresh Hresult Hlet Hctx ltac:(set_solver))).
      exact Htotal_target.
Qed.

(** The total [tlet] rule after splitting the body premise cofinally. *)
Lemma denot_tlet_total_semantic
    (Σ : gmap atom ty) (Γ : ctx) (τ1 τ2 : choice_ty) e1 e2 (L : aset)
    :
  erase_ctx_under Σ Γ ⊢ₑ e1 ⋮ erase_ty τ1 →
  erase_ctx_under Σ Γ ⊢ₑ tlete e1 e2 ⋮ erase_ty τ2 →
  entails_total (denot_ctx_in_env Σ Γ)
    (denot_ty_total_model_in_ctx_under Σ Γ τ1 e1) →
  (∀ x, x ∉ L →
    total_model_in_ctx_under Σ (CtxComma Γ (CtxBind x τ1)) τ2 (e2 ^^ x)) →
  entails_total (denot_ctx_in_env Σ Γ)
    (denot_ty_total_model_in_ctx_under Σ Γ τ2 (tlete e1 e2)).
Proof.
  intros Herase Hwflet IH1 Hbody m Hm.
  pose proof (IH1 m Hm) as Hmodel.
  pose proof (denot_ty_total_model_total Σ Γ τ1 e1 m Hmodel) as Htotal1.
  pose (Fresh :=
    L ∪ world_dom (m : World) ∪ dom (erase_ctx_under Σ Γ) ∪
    fv_tm e2 ∪ fv_cty τ2).
  pose (x := fresh_for Fresh).
  assert (HxFresh : x ∉ Fresh) by (subst x; apply fresh_for_not_in).
  assert (HxL : x ∉ L) by (subst Fresh; set_solver).
  assert (Hfresh : x ∉ world_dom (m : World)) by (subst Fresh; set_solver).
  assert (Hx_tlet :
    x ∉ dom (erase_ctx_under Σ Γ) ∪ fv_cty τ2 ∪ fv_tm e2)
    by (subst Fresh; set_solver).
  assert (Hclosed_erased :
    world_store_closed_on (dom (erase_ctx_under Σ Γ)) m).
  {
    pose proof (denot_ty_total_model_basic_ctx Σ Γ τ1 e1 m Hmodel)
      as Hbasic.
    intros σ Hσ.
    assert (Hdom_erase :
      dom (erase_ctx_under Σ Γ) = dom Σ ∪ ctx_dom Γ).
    { apply erase_ctx_under_dom_basic. exact Hbasic. }
    rewrite Hdom_erase.
    split.
    - exact (proj1 (denot_ctx_in_env_store_erased_typed
        Σ Γ m σ Hbasic Hm Hσ)).
    - exact (denot_ctx_in_env_store_erased_lc
        Σ Γ m σ Hbasic Hm Hσ).
  }
  assert (Hresult : ∀ σ, (m : World) σ →
    ∃ vx, subst_map (store_restrict σ (fv_tm e1)) e1 →* tret vx).
  { eapply expr_total_on_to_fv_result; eauto. }
  set (m' := let_result_world_on e1 x m Hfresh Hresult).
  assert (Hctx :
    m' ⊨ denot_ctx_in_env Σ (CtxComma Γ (CtxBind x τ1))).
  {
    subst m'. eapply tlet_split_premises_body_ctx_from_result; eauto.
  }
  pose proof (Hbody x HxL m' Hctx) as Hbody_model.
  exact (proj1
    (denot_ty_total_tlet_reduction
      Σ Γ τ1 τ2 e1 e2 m x Hfresh Hresult
      Herase Hwflet Hm Hmodel Hx_tlet)
    Hbody_model).
Qed.

Lemma denot_tlet_semantic
    (Σ : gmap atom ty) (Γ : ctx) (τ1 τ2 : choice_ty) e1 e2 (L : aset) :
  choice_typing_wf Σ Γ e1 τ1 →
  choice_typing_wf Σ Γ (tlete e1 e2) τ2 →
  (denot_ctx_in_env Σ Γ ⊫ denot_ty_in_ctx_under Σ Γ τ1 e1) →
  (∀ x, x ∉ L →
    denot_ctx_in_env Σ (CtxComma Γ (CtxBind x τ1)) ⊫
      denot_ty_in_ctx_under Σ (CtxComma Γ (CtxBind x τ1)) τ2 (e2 ^^ x)) →
  denot_ctx_in_env Σ Γ ⊫ denot_ty_in_ctx_under Σ Γ τ2 (tlete e1 e2).
Proof.
(** Placeholder: this is the non-total semantic [tlet] statement and should not
    be used as evidence that the [tlet] case is proved.  The current active
    route is the total statement [denot_tlet_total_semantic] above. *)
Admitted.
