(** * ChoiceType.DenotationRefinement

    Refinement-continuation naming and fiber-stability lemmas used by
    denotational typing proofs.  These facts are independent of the [tlet]
    proof itself and live with the type denotation layer. *)

From ChoiceType Require Export DenotationType.
From ChoiceLogic Require Import FormulaDerived.
From ChoiceType Require Import BasicStore QualifierProps.

Lemma denot_refinement_over_cont_insert_fresh_eq
    (D : aset) (Σ : gmap atom ty) x Tx b φ ν :
  x ∉ D ∪ qual_dom φ →
  dom Σ = D →
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> (<[x := Tx]> Σ))
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (lvars_of_atoms (qual_dom φν))
       (FOver (FTypeQualifier φν)))) =
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> Σ)
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (lvars_of_atoms (qual_dom φν))
       (FOver (FTypeQualifier φν)))).
Proof.
  intros Hx Hdom.
  f_equal.
  apply basic_world_formula_agree. intros z Hz.
  rewrite !lookup_insert.
  destruct (decide (z = ν)) as [->|Hzν].
  - rewrite !decide_True by reflexivity. reflexivity.
  - rewrite !decide_False by congruence.
    destruct (decide (z = x)) as [->|Hzx].
    + pose proof (qual_open_atom_dom_subset 0 ν φ x) as Hopen.
      assert (x ∈ qual_dom (qual_open_atom 0 ν φ)) by set_solver.
      pose proof (Hopen H) as Hxopen.
      set_solver.
    + repeat rewrite decide_False by congruence. reflexivity.
Qed.

Lemma denot_refinement_under_cont_insert_fresh_eq
    (D : aset) (Σ : gmap atom ty) x Tx b φ ν :
  x ∉ D ∪ qual_dom φ →
  dom Σ = D →
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> (<[x := Tx]> Σ))
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (lvars_of_atoms (qual_dom φν))
       (FUnder (FTypeQualifier φν)))) =
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> Σ)
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (lvars_of_atoms (qual_dom φν))
       (FUnder (FTypeQualifier φν)))).
Proof.
  intros Hx Hdom.
  f_equal.
  apply basic_world_formula_agree. intros z Hz.
  rewrite !lookup_insert.
  destruct (decide (z = ν)) as [->|Hzν].
  - rewrite !decide_True by reflexivity. reflexivity.
  - rewrite !decide_False by congruence.
    destruct (decide (z = x)) as [->|Hzx].
    + pose proof (qual_open_atom_dom_subset 0 ν φ x) as Hopen.
      assert (x ∈ qual_dom (qual_open_atom 0 ν φ)) by set_solver.
      pose proof (Hopen H) as Hxopen.
      set_solver.
    + repeat rewrite decide_False by congruence. reflexivity.
Qed.

(** The refinement continuations generated by [CTOver]/[CTUnder] mention only
    the ambient erased environment, the opened result coordinate, and the free
    variables recorded by the qualifier metadata.  This is the fv half of the
    hypothesis needed by [FExprCont_tlet_reduction]. *)
Lemma denot_refinement_over_cont_fv_subset
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  ∀ ν,
    formula_fv
      (let φν := qual_open_atom 0 ν φ in
       FAnd
         (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
         (FFibVars (lvars_of_atoms (qual_dom φν))
       (FOver (FTypeQualifier φν)))) ⊆
    D ∪ {[ν]}.
Proof.
  intros Hφ ν.
  destruct φ as [B d p]. simpl in Hφ.
  cbn [formula_fv].
  rewrite basic_world_formula_fv.
  simpl. rewrite lvars_fv_of_atoms.
  rewrite formula_fv_FTypeQualifier.
  unfold qual_open_atom, qual_dom in *; simpl in *.
  destruct (decide (0 ∈ B)); set_solver.
Qed.

Lemma denot_refinement_under_cont_fv_subset
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  ∀ ν,
    formula_fv
      (let φν := qual_open_atom 0 ν φ in
       FAnd
         (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
         (FFibVars (lvars_of_atoms (qual_dom φν))
       (FUnder (FTypeQualifier φν)))) ⊆
    D ∪ {[ν]}.
Proof.
  intros Hφ ν.
  destruct φ as [B d p]. simpl in Hφ.
  cbn [formula_fv].
  rewrite basic_world_formula_fv.
  simpl. rewrite lvars_fv_of_atoms.
  rewrite formula_fv_FTypeQualifier.
  unfold qual_open_atom, qual_dom in *; simpl in *.
  destruct (decide (0 ∈ B)); set_solver.
Qed.

Lemma qual_open_atom_dom_eq_member k x q :
  k ∈ qual_bvars q →
  qual_dom (qual_open_atom k x q) = {[x]} ∪ qual_dom q.
Proof.
  destruct q as [B d p]. unfold qual_open_atom, qual_bvars, qual_dom.
  simpl. intros Hk. rewrite decide_True by exact Hk. reflexivity.
Qed.

Lemma qual_open_atom_eq_not_member k x q :
  k ∉ qual_bvars q →
  qual_open_atom k x q = q.
Proof.
  destruct q as [B d p]. unfold qual_open_atom, qual_bvars.
  simpl. intros Hk. rewrite decide_False by exact Hk. reflexivity.
Qed.

Lemma qual_open_atom_dom_union_singleton k x q :
  {[x]} ∪ qual_dom (qual_open_atom k x q) = {[x]} ∪ qual_dom q.
Proof.
  destruct q as [B d p]. unfold qual_open_atom, qual_dom, qual_bvars.
  simpl. destruct (decide (k ∈ B)); set_solver.
Qed.

Lemma formula_store_equiv_lift_open_over_rename_fresh k x y q :
  k ∈ qual_bvars q →
  x ∉ qual_dom q →
  y ∉ qual_dom q →
  formula_store_equiv
    (formula_rename_atom x y
      (FOver (FTypeQualifier (qual_open_atom k x q))))
    (FOver (FTypeQualifier (qual_open_atom k y q))).
Proof.
  (* Legacy explicit rename route; replaced by LN open/cofinite bridge. *)
Admitted.

Lemma formula_store_equiv_lift_open_under_rename_fresh k x y q :
  k ∈ qual_bvars q →
  x ∉ qual_dom q →
  y ∉ qual_dom q →
  formula_store_equiv
    (formula_rename_atom x y
      (FUnder (FTypeQualifier (qual_open_atom k x q))))
    (FUnder (FTypeQualifier (qual_open_atom k y q))).
Proof.
  (* Legacy explicit rename route; replaced by LN open/cofinite bridge. *)
Admitted.

Lemma denot_refinement_over_fib_rename_stable
    (D : aset) φ :
  qual_dom φ ⊆ D →
  ∀ x y m,
    x ∉ D →
    y ∉ D →
    m ⊨ formula_rename_atom x y
      (let φx := qual_open_atom 0 x φ in
       FFibVars (lvars_of_atoms (qual_dom φx))
       (FOver (FTypeQualifier φx))) ↔
    m ⊨
      (let φy := qual_open_atom 0 y φ in
       FFibVars (lvars_of_atoms (qual_dom φy))
       (FOver (FTypeQualifier φy))).
Proof.
  (* Legacy explicit rename route; replaced by LN open/cofinite bridge. *)
Admitted.

Lemma denot_refinement_under_fib_rename_stable
    (D : aset) φ :
  qual_dom φ ⊆ D →
  ∀ x y m,
    x ∉ D →
    y ∉ D →
    m ⊨ formula_rename_atom x y
      (let φx := qual_open_atom 0 x φ in
       FFibVars (lvars_of_atoms (qual_dom φx))
       (FUnder (FTypeQualifier φx))) ↔
    m ⊨
      (let φy := qual_open_atom 0 y φ in
       FFibVars (lvars_of_atoms (qual_dom φy))
       (FUnder (FTypeQualifier φy))).
Proof.
  (* Legacy explicit rename route; replaced by LN open/cofinite bridge. *)
Admitted.

Lemma denot_refinement_over_cont_rename_stable
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  formula_family_rename_stable_on D (fun ν =>
    let φν := qual_open_atom 0 ν φ in
    FAnd
      (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
      (FFibVars (lvars_of_atoms (qual_dom φν))
       (FOver (FTypeQualifier φν)))).
Proof.
  intros Hφ x y m HxD HyD.
  unfold formula_family_rename_stable_on.
  simpl.
  split; intros H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      apply (proj1 Hbasic).
      replace ({[x]} ∪ qual_dom φ) with
          ({[x]} ∪ qual_dom (qual_open_atom 0 x φ))
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply res_models_and_elim_l in H. exact H.
    + pose proof (denot_refinement_over_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj1 Hfib).
      apply res_models_and_elim_r in H. exact H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      replace ({[x]} ∪ qual_dom (qual_open_atom 0 x φ)) with
          ({[x]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply (proj2 Hbasic).
      apply res_models_and_elim_l in H.
      replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ) in H
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      exact H.
    + pose proof (denot_refinement_over_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj2 Hfib).
      apply res_models_and_elim_r in H. exact H.
Qed.

Lemma denot_refinement_under_cont_rename_stable
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  formula_family_rename_stable_on D (fun ν =>
    let φν := qual_open_atom 0 ν φ in
    FAnd
      (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
      (FFibVars (lvars_of_atoms (qual_dom φν))
       (FUnder (FTypeQualifier φν)))).
Proof.
  intros Hφ x y m HxD HyD.
  unfold formula_family_rename_stable_on.
  simpl.
  split; intros H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      apply (proj1 Hbasic).
      replace ({[x]} ∪ qual_dom φ) with
          ({[x]} ∪ qual_dom (qual_open_atom 0 x φ))
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply res_models_and_elim_l in H. exact H.
    + pose proof (denot_refinement_under_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj1 Hfib).
      apply res_models_and_elim_r in H. exact H.
  - apply res_models_and_intro_from_models.
    + replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      pose proof (res_models_basic_world_formula_rename_insert_fresh
        Σ (qual_dom φ) x y (TBase b) m ltac:(set_solver) ltac:(set_solver))
        as Hbasic.
      replace ({[x]} ∪ qual_dom (qual_open_atom 0 x φ)) with
          ({[x]} ∪ qual_dom φ)
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      apply (proj2 Hbasic).
      apply res_models_and_elim_l in H.
      replace ({[y]} ∪ qual_dom (qual_open_atom 0 y φ)) with
          ({[y]} ∪ qual_dom φ) in H
        by (rewrite qual_open_atom_dom_union_singleton; reflexivity).
      exact H.
    + pose proof (denot_refinement_under_fib_rename_stable
        D φ Hφ x y m HxD HyD) as Hfib.
      apply (proj2 Hfib).
      apply res_models_and_elim_r in H. exact H.
Qed.
