(** * ChoiceType.DenotationRefinement

    Refinement-continuation naming and fiber-stability lemmas used by
    denotational typing proofs.  These facts are independent of the [tlet]
    proof itself and live with the type denotation layer. *)

From ChoiceType Require Export DenotationType.
From ChoiceLogic Require Import FormulaDerived.
From ChoiceType Require Import BasicStore QualifierProps.

Lemma denot_refinement_over_cont_insert_fresh_eq
    (D : aset) (Σ : gmap atom ty) x Tx b φ ν :
  x ∉ D ∪ qual_dom φ →
  dom Σ = D →
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> (<[x := Tx]> Σ))
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (qual_vars φν)
       (FOver (FTypeQualifier φν)))) =
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> Σ)
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (qual_vars φν)
       (FOver (FTypeQualifier φν)))).
Proof.
  intros Hx Hdom.
  f_equal.
  apply basic_world_formula_agree. intros z Hz.
  rewrite !lookup_insert.
  destruct (decide (z = ν)) as [->|Hzν].
  - rewrite !decide_True by reflexivity. reflexivity.
  - rewrite !decide_False by congruence.
    destruct (decide (z = x)) as [->|Hzx].
    + pose proof (qual_open_atom_dom_subset 0 ν φ x) as Hopen.
      assert (x ∈ qual_dom (qual_open_atom 0 ν φ)) by set_solver.
      pose proof (Hopen H) as Hxopen.
      set_solver.
    + repeat rewrite decide_False by congruence. reflexivity.
Qed.

Lemma denot_refinement_under_cont_insert_fresh_eq
    (D : aset) (Σ : gmap atom ty) x Tx b φ ν :
  x ∉ D ∪ qual_dom φ →
  dom Σ = D →
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> (<[x := Tx]> Σ))
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (qual_vars φν)
       (FUnder (FTypeQualifier φν)))) =
  (let φν := qual_open_atom 0 ν φ in
   FAnd
     (basic_world_formula (<[ν := TBase b]> Σ)
       ({[ν]} ∪ qual_dom φν))
     (FFibVars (qual_vars φν)
       (FUnder (FTypeQualifier φν)))).
Proof.
  intros Hx Hdom.
  f_equal.
  apply basic_world_formula_agree. intros z Hz.
  rewrite !lookup_insert.
  destruct (decide (z = ν)) as [->|Hzν].
  - rewrite !decide_True by reflexivity. reflexivity.
  - rewrite !decide_False by congruence.
    destruct (decide (z = x)) as [->|Hzx].
    + pose proof (qual_open_atom_dom_subset 0 ν φ x) as Hopen.
      assert (x ∈ qual_dom (qual_open_atom 0 ν φ)) by set_solver.
      pose proof (Hopen H) as Hxopen.
      set_solver.
    + repeat rewrite decide_False by congruence. reflexivity.
Qed.

(** The refinement continuations generated by [CTOver]/[CTUnder] mention only
    the ambient erased environment, the opened result coordinate, and the free
    variables recorded by the qualifier metadata.  This is the fv half of the
    hypothesis needed by [FExprCont_tlet_reduction]. *)
Lemma denot_refinement_over_cont_fv_subset
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  ∀ ν,
    formula_fv
      (let φν := qual_open_atom 0 ν φ in
       FAnd
         (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
         (FFibVars (qual_vars φν)
       (FOver (FTypeQualifier φν)))) ⊆
    D ∪ {[ν]}.
Proof.
  intros Hφ ν.
  cbn [formula_fv].
  rewrite basic_world_formula_fv.
  simpl.
  rewrite formula_fv_FTypeQualifier.
  pose proof (qual_open_atom_dom_subset 0 ν φ) as Hsubset.
  destruct (qual_open_atom 0 ν φ) as [Dν pν].
  cbn [qual_dom qual_vars].
  set_solver.
Qed.

Lemma denot_refinement_under_cont_fv_subset
    (D : aset) (Σ : gmap atom ty) b φ :
  qual_dom φ ⊆ D →
  ∀ ν,
    formula_fv
      (let φν := qual_open_atom 0 ν φ in
       FAnd
         (basic_world_formula (<[ν := TBase b]> Σ) ({[ν]} ∪ qual_dom φν))
         (FFibVars (qual_vars φν)
       (FUnder (FTypeQualifier φν)))) ⊆
    D ∪ {[ν]}.
Proof.
  intros Hφ ν.
  cbn [formula_fv].
  rewrite basic_world_formula_fv.
  simpl.
  rewrite formula_fv_FTypeQualifier.
  pose proof (qual_open_atom_dom_subset 0 ν φ) as Hsubset.
  destruct (qual_open_atom 0 ν φ) as [Dν pν].
  cbn [qual_dom qual_vars].
  set_solver.
Qed.

Lemma qual_open_atom_dom_eq_member k x q :
  k ∈ qual_bvars q →
  qual_dom (qual_open_atom k x q) = {[x]} ∪ qual_dom q.
Proof.
Admitted.

Lemma qual_open_atom_eq_not_member k x q :
  k ∉ qual_bvars q →
  qual_open_atom k x q = q.
Proof.
  destruct q as [B p]. unfold qual_open_atom, qual_bvars.
  simpl. intros Hk. rewrite decide_False by exact Hk. reflexivity.
Qed.
